/**
 * Demo unit catalog: the tables generated by scripts/gen-data.ts from docs/design/roster.json and
 * scripts/unit-texts.json (buildable-by evaluated with @faf/rules at generation time). Only gallery, tests
 * and benchmarks use it; the game builds its own catalog from the compiled blueprints (MS4, see
 * docs/status/track-hud.md §10) and writes it to `HudModel.units`.
 */
import { createUnitCatalog } from '../data/catalog.ts';
import type { UnitCatalog } from '../data/catalog.ts';
import { BUILD_TABLE } from '../data/build-table.gen.ts';
import { ROSTER } from '../data/roster.gen.ts';

let demo: UnitCatalog | null = null;

/** The generated demo catalog (one shared instance, so per-catalog memoisation is shared as well). */
export function demoUnitCatalog(): UnitCatalog {
  demo ??= createUnitCatalog({ units: ROSTER, buildTable: BUILD_TABLE }, 'demo');
  return demo;
}
