// @vitest-environment happy-dom
import { describe, it, expect } from 'vitest';
import { MainMenu, SkirmishSetup, GameMenu, Settings, LoadingScreen, ScoreScreen, createHudModel, seedMenus, setLocale, validateSkirmish, swapStart, validateSettings, DEFAULT_SETTINGS, seriesMax, seriesPath, sampleAt } from '../../src/index.ts';
import { renderWithHud, fireEvent, flushSignals } from '../support/index.tsx';
function model() { const m = createHudModel(); seedMenus(m); return m; }
describe('menu contracts', () => {
    it('main menu focuses skirmish and wraps enabled items', () => { const r = renderWithHud(<MainMenu />, { model: model() }); const first = r.getByRole('button', { name: /Gefecht/ }); expect(document.activeElement).toBe(first); fireEvent.keyDown(first, { key: 'ArrowDown' }); expect(document.activeElement?.textContent).toContain('Einstellungen'); fireEvent.click(document.activeElement!); expect(r.log.at(-1)).toEqual({ name: 'navigate', args: ['settings'] }); });
    it('starts a complete valid config and swaps occupied starts', () => { const m = model(), r = renderWithHud(<SkirmishSetup />, { model: m }); fireEvent.click(r.getByRole('button', { name: 'Gefecht starten' })); expect(r.log.at(-1)).toEqual({ name: 'startSkirmish', args: [{ mapId: 'setons', slots: m.menus.skirmish.slots.value, rules: m.menus.skirmish.rules.value }] }); fireEvent.click(r.getByRole('button', { name: 'Startposition 2' })); expect(r.log.at(-1)?.name).toBe('updateSkirmish'); expect(swapStart(m.menus.skirmish.slots.value, 0, 1).map(s => s.start)).toEqual([1, 0]); const cfg = { mapId: 'setons', slots: m.menus.skirmish.slots.value.map(s => ({ ...s, color: 'red' })), rules: m.menus.skirmish.rules.value }; expect(validateSkirmish(cfg, m.menus.skirmish.maps.value)).toBe('ui.skirmish.duplicateColor'); });
    it('blocks duplicate-colour starts in the actual control', () => { const m = model(); m.menus.skirmish.slots.value = m.menus.skirmish.slots.value.map(s => ({ ...s, color: 'red' })); const r = renderWithHud(<SkirmishSetup />, { model: m }); expect((r.getByRole('button', { name: 'Gefecht starten' }) as HTMLButtonElement).disabled).toBe(true); });
    it('traps modal focus and Escape resumes, surrender requires confirmation', async () => { const m = model(); m.menus.gameMenu.open.value = true; const r = renderWithHud(<GameMenu />, { model: m }), buttons = r.getAllByRole('button'); buttons[0]!.focus(); fireEvent.keyDown(buttons[0]!, { key: 'Tab', shiftKey: true }); expect(document.activeElement).toBe(buttons.at(-1)); fireEvent.keyDown(buttons.at(-1)!, { key: 'Escape' }); expect(r.log.at(-1)?.name).toBe('resume'); fireEvent.click(r.getByRole('button', { name: 'Aufgeben' })); await flushSignals(); fireEvent.click(r.getByRole('button', { name: 'Bestätigen' })); expect(r.log.at(-1)?.name).toBe('surrender'); });
    it('settings produce typed values and support live locale replacement', async () => { const r = renderWithHud(<Settings />, { model: model() }); fireEvent.input(r.getByRole('slider', { name: 'Render-Skalierung' }), { target: { value: '.8' } }); expect(r.log.at(-1)).toEqual({ name: 'setSetting', args: ['renderScale', .8] }); fireEvent.click(r.getByRole('switch', { name: 'Bloom' })); expect(r.log.at(-1)).toEqual({ name: 'setSetting', args: ['bloom', false] }); fireEvent.click(r.getByRole('button', { name: 'Zurücksetzen' })); expect(r.log.at(-1)?.name).toBe('resetSettings'); await flushSignals(() => setLocale('en')); expect(r.getByRole('heading', { name: 'Settings' })).toBeTruthy(); expect(validateSettings(DEFAULT_SETTINGS)).toEqual([]); expect(validateSettings({ ...DEFAULT_SETTINGS, renderScale: Infinity, volMusic: -1 })).toEqual(['renderScale', 'volMusic']); });
    it('renders loading failure commands and marks score winners', () => { const m = model(); m.menus.loading.error.value = 'Demo failure'; const r = renderWithHud(<LoadingScreen />, { model: m }); fireEvent.click(r.getByRole('button', { name: 'Erneut' })); expect(r.log.at(-1)?.name).toBe('retryLoading'); r.unmount(); const score = renderWithHud(<ScoreScreen />, { model: m }); expect(score.container.querySelectorAll('.is-better').length).toBe(6); fireEvent.click(score.getByRole('button', { name: 'Replay speichern' })); expect(score.log.at(-1)?.name).toBe('saveReplay'); });
    it('uses shared graph scale and clamps crosshair sampling', () => { const s = { id: 'massIncome' as const, stepS: 30, self: [0, 10], enemy: [0, 20] }; expect(seriesMax(s)).toBe(20); expect(seriesPath(s.self, 20)).toBe('M40,170 L460,95'); expect(sampleAt(s, 2)).toEqual({ index: 1, timeS: 30, self: 10, enemy: 20 }); });
});
