services:
  game:
    networks:
      - default
      - dokploy-network
    labels:
      traefik.enable: "true"
      traefik.docker.network: dokploy-network
      traefik.http.routers.flow-and-fire.rule: Host(`flow-and-fire.logge.top`)
      traefik.http.routers.flow-and-fire.entrypoints: websecure
      traefik.http.routers.flow-and-fire.tls: "true"
      traefik.http.services.flow-and-fire.loadbalancer.server.port: "8080"
networks:
  dokploy-network:
    external: true
