/** MS4 values from docs/design/roster.md §§4,9. Own faction IDs and placeholder assets. */
import { defineUnit } from '../../../../packages/blueprints/src/define.ts';
const structures = { health: { max: 400 }, motion: { layer: 'land' as const, speed: 0, accel: 0, turnRateDeg: 0, sizeClass: 2, footprint: [2, 2] as const, maxSlope: 0.3, turnInPlace: false }, intel: { vision: 16 }, wreck: { massFraction: 0.9, hpFraction: 0.5 }, veterancy: 'none' as const };
const view = { iconThreshold: 10, icon: 'structure_generic' as const, placeholder: { hull: 'box' as const, size: [1.8, 1, 1.8] as const }, lod: [80, 240] as const };
const buildableBy = '(ENGINEER & (TECH1 | TECH2 | TECH3)) | COMMAND';
export default [
    defineUnit({id:'core:str_t1_estorage',categories:['STRUCTURE','ECONOMIC','ENERGYSTORAGE','TECH1'],sim:{...structures,economy:{mass:120,energy:1200,buildTime:120,buildableBy,energyStorage:5000}},view:{...view,mesh:'units/varkan/str_t1_estore',hotkeySlot:'R'}}),
    defineUnit({ id: 'core:cmd_commander', categories: ['LAND', 'MOBILE', 'DIRECTFIRE', 'COMMAND', 'ENGINEER', 'RECLAIM', 'REPAIR', 'UNIQUE'], sim: { upgradesTo: 'core:cmd_commander_engineering', health: { max: 12000 }, motion: { layer: 'land', speed: 1.7, accel: 3, turnRateDeg: 90, sizeClass: 2, footprint: [2, 2], maxSlope: 0.6, radius: 0.7 }, intel: { vision: 26 }, deathWeapon:'core:wpn_plumb_break', weapons: [{id:'cannon',ref:'core:wpn_reeve_cannon',part:'hull',arcDeg:360,yawRateDeg:120,layers:['land'],priorities:['COMMAND','MOBILE & LAND','STRUCTURE']}], economy: { mass: 2000, energy: 5000000, buildTime: 6000000, buildPower: 10, buildRange: 5, massIncome: 1, energyIncome: 20, massStorage: 650, energyStorage: 3900 } }, view: { mesh: 'units/varkan/cmd_commander', placeholder: { hull: 'box', size: [2, 2.4, 2] }, icon: 'commander', iconThreshold: 12, lod: [80, 240] } }),
    defineUnit({ id: 'core:cmd_commander_engineering', extends: 'core:cmd_commander', sim: { upgradesTo: 'core:cmd_commander_armored', health: { max: 16000 }, economy: { mass: 300, energy: 3000, buildTime: 600, buildPower: 20 } } }),
    defineUnit({ id: 'core:cmd_commander_armored', extends: 'core:cmd_commander_engineering', sim: { upgradesTo: null, health: { max: 24000 }, economy: { mass: 400, energy: 5000, buildTime: 800 } } }),
    defineUnit({ id: 'core:str_t1_mex', categories: ['STRUCTURE', 'ECONOMIC', 'MASSEXTRACTION', 'TECH1', 'SIZE4'], sim: { ...structures, economy: { mass: 36, energy: 360, buildTime: 60, buildableBy, buildPower: 10, massIncome: 2, energyUpkeep: 2, spotKind: 'mass' } }, view: { ...view, mesh: 'units/varkan/str_t1_mex', hotkeySlot: 'Q' } }),
    defineUnit({ id: 'core:str_t1_pgen', categories: ['STRUCTURE', 'ECONOMIC', 'ENERGYPRODUCTION', 'TECH1', 'SIZE4'], sim: { ...structures, health: { max: 620 }, economy: { mass: 75, energy: 750, buildTime: 125, buildableBy, energyIncome: 20 } }, view: { ...view, mesh: 'units/varkan/str_t1_pgen', hotkeySlot: 'W' } }),
];
