/**
 * Offline generator for the trigonometry LUTs of @faf/fixed (PLAN §3.3).
 *
 * Runs in Node with float math (Math.sin/Math.atan) — never at simulation time. Outputs:
 *   luts/sin_quarter.bin  4096 × u16 LE: round(sin(k · (π/2) / 4096) · 4096), k = 0..4095
 *   luts/atan.bin         1024 × u16 LE: round(atan(k / 1024) · 65536 / 2π), k = 0..1023
 *   src/luts.generated.ts the same data as integer literal arrays + xxHash32 of each .bin
 *
 * Usage: pnpm --filter @faf/fixed gen:luts  (the .bin files are checked in; tests pin their hash)
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { xxHash32 } from '../src/xxhash32.ts';

export const SIN_QUARTER_SIZE = 4096;
export const ATAN_SIZE = 1024;

export function computeSinQuarter(): Uint16Array {
  const out = new Uint16Array(SIN_QUARTER_SIZE);
  for (let k = 0; k < SIN_QUARTER_SIZE; k++) {
    out[k] = Math.round(Math.sin((k * Math.PI) / 2 / SIN_QUARTER_SIZE) * 4096);
  }
  return out;
}

export function computeAtan(): Uint16Array {
  const out = new Uint16Array(ATAN_SIZE);
  for (let k = 0; k < ATAN_SIZE; k++) {
    out[k] = Math.round((Math.atan(k / ATAN_SIZE) * 65536) / (2 * Math.PI));
  }
  return out;
}

export function toLeBytes(values: Uint16Array): Uint8Array {
  const bytes = new Uint8Array(values.length * 2);
  const view = new DataView(bytes.buffer);
  for (let i = 0; i < values.length; i++) view.setUint16(i * 2, values[i] ?? 0, true);
  return bytes;
}

function formatArray(name: string, doc: string, values: Uint16Array): string {
  const lines: string[] = [];
  for (let i = 0; i < values.length; i += 24) {
    lines.push('  ' + Array.from(values.subarray(i, i + 24)).join(', ') + ',');
  }
  return `/** ${doc} */\nexport const ${name}: readonly number[] = [\n${lines.join('\n')}\n];\n`;
}

function hex(n: number): string {
  return '0x' + n.toString(16).toUpperCase().padStart(8, '0');
}

function main(): void {
  const pkgDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const sin = computeSinQuarter();
  const atan = computeAtan();
  const sinBytes = toLeBytes(sin);
  const atanBytes = toLeBytes(atan);
  mkdirSync(resolve(pkgDir, 'luts'), { recursive: true });
  writeFileSync(resolve(pkgDir, 'luts/sin_quarter.bin'), sinBytes);
  writeFileSync(resolve(pkgDir, 'luts/atan.bin'), atanBytes);
  const sinHash = xxHash32(sinBytes, 0, sinBytes.length, 0);
  const atanHash = xxHash32(atanBytes, 0, atanBytes.length, 0);
  const ts =
    '// GENERATED by packages/fixed/scripts/gen-luts.ts — do not edit. Source of truth: luts/*.bin.\n\n' +
    `/** xxHash32 (seed 0) of luts/sin_quarter.bin. */\nexport const SIN_QUARTER_XXH32 = ${hex(sinHash)};\n\n` +
    `/** xxHash32 (seed 0) of luts/atan.bin. */\nexport const ATAN_XXH32 = ${hex(atanHash)};\n\n` +
    formatArray('SIN_QUARTER_DATA', 'round(sin(k·(π/2)/4096)·4096), k = 0..4095 (Fx).', sin) +
    '\n' +
    formatArray('ATAN_DATA', 'round(atan(k/1024)·65536/2π), k = 0..1023 (Ang16).', atan);
  writeFileSync(resolve(pkgDir, 'src/luts.generated.ts'), ts);
  console.log(`sin_quarter.bin ${sinBytes.length} B xxh32=${hex(sinHash)}`);
  console.log(`atan.bin        ${atanBytes.length} B xxh32=${hex(atanHash)}`);
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
