import { useLayoutEffect, useRef } from 'preact/hooks';
import { useHud, useCommands } from '../../model/index.ts';
import { t } from '../../i18n/t.ts';
import { fmtTime } from '../../format/index.ts';
import { Panel, PanelHead, Button } from '../../ui/index.ts';
import { MenuShell } from '../shared/Shell.tsx';
export function MainMenu() {
    const m = useHud(), c = useCommands(), ref = useRef<HTMLElement>(null), last = m.menus.main.lastMatch.value, wordmark = t('ui.menu.title').split('&');
    useLayoutEffect(() => { ref.current?.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus(); }, []);
    return <MenuShell title={t('ui.menu.title')} component="MainMenu" footer={<span>{t('ui.menu.build', { build: m.menus.main.build.value, sim: m.menus.main.simId.value, transport: m.menus.main.transport.value, preset: m.menus.main.preset.value })}</span>}><main class="main"><div><div class="logo">{wordmark[0]}<span class="amp">{'&'}</span><br/><span class="fire">{wordmark[1]}</span></div><div class="tagline">{t('ui.menu.tagline')}</div><nav class="mainnav" ref={ref} onKeyDown={(e) => { if (!['ArrowUp', 'ArrowDown'].includes(e.key))
        return; e.preventDefault(); const buttons = [...e.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')], index = buttons.indexOf(document.activeElement as HTMLButtonElement); buttons[(index + (e.key === 'ArrowDown' ? 1 : buttons.length - 1)) % buttons.length]?.focus(); }}>{(['skirmish', 'replays', 'settings', 'tutorial', 'credits'] as const).map((screen) => <button class={`navbtn ${screen === 'skirmish' ? 'is-primary' : ''}`} disabled={screen === 'tutorial' || (screen === 'replays' && !m.menus.main.replaysAvailable.value)} onClick={() => c.navigate(screen)} key={screen}><span>›</span><span>{t(`ui.menu.${screen}`)}</span>{((screen === 'replays' && !m.menus.main.replaysAvailable.value) || screen === 'tutorial') && <small>{t(screen === 'replays' ? 'ui.menu.locked' : 'ui.menu.post')}</small>}</button>)}</nav></div><div class="side"><svg class="menu-main-emblem" viewBox="0 0 200 200" aria-hidden="true"><circle cx="100" cy="100" r="82" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="100" cy="100" r="68" fill="none" stroke="currentColor"/><path d="M100 35 133 103 100 164 67 103Z" fill="none" stroke="currentColor" stroke-width="4"/><path d="M100 45V152M70 103H130" stroke="currentColor" stroke-width="3"/></svg><Panel class="card-m"><PanelHead title={t('ui.menu.last')}/><div class="card-m__body">{last ? <><b>{last.mapName}</b><span>{t(`ui.score.${last.verdict}`)} · {fmtTime(last.durationS)} · {last.opponent}</span><div><Button disabled={!last.hasReplay} onClick={() => c.watchReplay()}>{t('ui.menu.replay')}</Button><Button onClick={() => c.rematch()}>{t('ui.menu.rematch')}</Button></div></> : <span>{t('ui.menu.empty')}</span>}</div></Panel></div></main></MenuShell>;
}
