// Generated by packages/hud/scripts/gen-data.ts from docs/design/roster.json (buildableBy evaluated with @faf/rules). Do not edit; run `pnpm --filter @faf/hud run gen`.

/** Builder type id → type ids it can build directly (roster order). Upgrade-only tiers never appear. */
export const BUILD_TABLE: Readonly<Record<string, readonly string[]>> = {
  "core:cmd_commander": ["core:str_t1_mex","core:str_t1_pgen","core:str_t1_hydro","core:str_t1_mstore","core:str_t1_estore","core:str_t1_fac_land","core:str_t1_fac_air","core:str_t1_pd","core:str_t1_aa","core:str_t1_wall","core:str_t1_radar"],
  "core:lnd_t1_engineer": ["core:str_t1_mex","core:str_t1_pgen","core:str_t1_hydro","core:str_t1_mstore","core:str_t1_estore","core:str_t1_fac_land","core:str_t1_fac_air","core:str_t1_pd","core:str_t1_aa","core:str_t1_wall","core:str_t1_radar"],
  "core:lnd_t2_engineer": ["core:str_t1_mex","core:str_t2_mex","core:str_t1_pgen","core:str_t2_pgen","core:str_t1_hydro","core:str_t1_mstore","core:str_t1_estore","core:str_t1_fac_land","core:str_t1_fac_air","core:str_t1_pd","core:str_t2_pd","core:str_t1_aa","core:str_t2_aa","core:str_t1_wall","core:str_t1_radar","core:str_t2_shield","core:str_t2_arty"],
  "core:lnd_t3_engineer": ["core:str_t1_mex","core:str_t2_mex","core:str_t3_mex","core:str_t1_pgen","core:str_t2_pgen","core:str_t3_pgen","core:str_t1_hydro","core:str_t1_mstore","core:str_t1_estore","core:str_t1_fac_land","core:str_t1_fac_air","core:str_t1_pd","core:str_t2_pd","core:str_t1_aa","core:str_t2_aa","core:str_t3_sam","core:str_t1_wall","core:str_t1_radar","core:str_t2_shield","core:str_t2_arty","core:str_t3_arty","core:exp_lnd_walker","core:exp_lnd_foundry","core:exp_air_gunship","core:exp_str_arty","core:exp_str_eco","core:exp_str_shield"],
  "core:str_t1_fac_land": ["core:lnd_t1_engineer","core:lnd_t1_scout","core:lnd_t1_bot","core:lnd_t1_tank","core:lnd_t1_arty","core:lnd_t1_aa"],
  "core:str_t2_fac_land": ["core:lnd_t1_engineer","core:lnd_t2_engineer","core:lnd_t1_scout","core:lnd_t1_bot","core:lnd_t1_tank","core:lnd_t1_arty","core:lnd_t1_aa","core:lnd_t2_tank","core:lnd_t2_mml","core:lnd_t2_aa","core:lnd_t2_shield","core:lnd_t2_bot"],
  "core:str_t3_fac_land": ["core:lnd_t1_engineer","core:lnd_t2_engineer","core:lnd_t3_engineer","core:lnd_t1_scout","core:lnd_t1_bot","core:lnd_t1_tank","core:lnd_t1_arty","core:lnd_t1_aa","core:lnd_t2_tank","core:lnd_t2_mml","core:lnd_t2_aa","core:lnd_t2_shield","core:lnd_t2_bot","core:lnd_t3_bot","core:lnd_t3_arty","core:lnd_t3_sniper","core:lnd_t3_aa"],
  "core:str_t1_fac_air": ["core:air_t1_scout","core:air_t1_fighter","core:air_t1_bomber"],
  "core:str_t2_fac_air": ["core:air_t1_scout","core:air_t1_fighter","core:air_t1_bomber","core:air_t2_gunship","core:air_t2_fbomber"],
  "core:exp_lnd_foundry": [],
};
