"""Compile the checked-in ImageGen tile to one tiny repeatable R8 material sample.

Run from the repository root: python3 tools/assets-pipeline/scripts/armor-surface.py
Requires Pillow. No image-generation API call is made.
"""
import base64
import hashlib
import statistics
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[3]
source = root / "content/textures/varkan/armor-surface-v1.png"
size = 128
image = Image.open(source).convert("L").resize((size, size), Image.Resampling.LANCZOS)
values = list(image.tobytes())
mean = statistics.mean(values)
deviation = max(statistics.pstdev(values), 1)
pixels = [max(64, min(192, round(128 + (value - mean) * 20 / deviation))) for value in values]
# A small periodic edge band joins opposite edges without large tiled landmarks.
for y in range(size):
    for distance in range(8):
        a, b = y * size + distance, y * size + size - 1 - distance
        blend = (1 - distance / 8) * 0.5
        va, vb = pixels[a], pixels[b]
        pixels[a], pixels[b] = round(va + (vb - va) * blend), round(vb + (va - vb) * blend)
for x in range(size):
    for distance in range(8):
        a, b = distance * size + x, (size - 1 - distance) * size + x
        blend = (1 - distance / 8) * 0.5
        va, vb = pixels[a], pixels[b]
        pixels[a], pixels[b] = round(va + (vb - va) * blend), round(vb + (va - vb) * blend)
data = bytes(pixels)
compiled = Image.frombytes("L", (size, size), data)
compiled.save(root / "content/textures/varkan/armor-surface-v1-r8.png", optimize=True)
encoded = base64.b64encode(data).decode("ascii")
shader = """
// Bind-space triplanar projection follows the animated part without swimming.
float armorGrain(sampler2D surfaceMap, vec3 p, vec3 normal, float weight) {
  vec3 blend = pow(abs(normalize(normal)), vec3(4.0));
  blend /= max(dot(blend, vec3(1.0)), 0.0001);
  vec3 tile = p * 1.25;
  float sampleValue = texture(surfaceMap, tile.yz).r * blend.x
    + texture(surfaceMap, tile.xz).r * blend.y
    + texture(surfaceMap, tile.xy).r * blend.z;
  // Mean-preserving albedo modulation only. No normal/roughness or baked light claims.
  return 1.0 + (sampleValue - 128.0 / 255.0) * 1.15 * weight;
}
"""
module = (
    "/** Generated by tools/assets-pipeline/scripts/armor-surface.py. Do not edit.\n"
    f" * Source SHA-256: {hashlib.sha256(source.read_bytes()).hexdigest()}\n"
    " * ImageGen source and prompt: content/textures/varkan/README.md.\n"
    " * Same generated module in render and model viewer keeps each package independent. */\n"
    f"export const ARMOR_SURFACE_SIZE = {size};\n"
    f"const SAMPLE = '{encoded}';\n"
    "export function armorSurfacePixels(): Uint8Array<ArrayBuffer> {\n"
    "  return Uint8Array.from(atob(SAMPLE), (c) => c.charCodeAt(0));\n"
    "}\n"
    f"export const ARMOR_SURFACE_GLSL = {shader!r};\n"
)
# Python repr has real JS-compatible escaped newlines and quotes here.
for destination in [
    root / "packages/render/src/units/armor-surface.ts",
    root / "apps/model-viewer/src/armor-surface.ts",
]:
    destination.write_text(module)
print(f"Compiled {size}x{size} R8 sample, {len(data)} bytes, SHA-256 {hashlib.sha256(data).hexdigest()}")
