import { useState } from 'preact/hooks';
import { useHud, useCommands } from '../../model/index.ts';
import type { ScoreSeries } from '../../model/menus/score.ts';
import { SCORE_TABS } from '../../model/menus/score.ts';
import { tDynamic as t } from '../../i18n/t.ts';
import { fmtInt, fmtTime } from '../../format/index.ts';
import { Button, Tabs, Tab } from '../../ui/index.ts';
import { MenuShell } from '../shared/Shell.tsx';
import { seriesMax, seriesPath, sampleAt, isBetter } from './graph.ts';
export function ScoreGraph({ series }: {
    readonly series: ScoreSeries;
}) { const [sample, setSample] = useState<ReturnType<typeof sampleAt> | null>(null), max = seriesMax(series); return <figure><figcaption>{t(`ui.score.${series.id}`)} · {t('ui.score.self')} / {t('ui.score.enemy')}</figcaption><svg class="score-chart" viewBox="0 0 650 200" role="img" aria-label={t(`ui.score.${series.id}`)} onPointerMove={e => { const r = e.currentTarget.getBoundingClientRect(); setSample(sampleAt(series, Math.max(0, Math.min(1, (e.clientX - r.left) / r.width)))); }} onPointerLeave={() => setSample(null)}><path d="M40 20V170H460" fill="none" stroke="var(--line)"/>{[0, .5, 1].map(v => <text key={v} x="0" y={170 - v * 150}>{fmtInt(max * v)}</text>)}<path class="series-self" d={seriesPath(series.self, max)} fill="none" stroke-width="2"/><path class="series-enemy" d={seriesPath(series.enemy, max)} fill="none" stroke-width="2" stroke-dasharray="5 4"/><text x="470" y={170 - (series.self.at(-1) ?? 0) / max * 150}>{t('ui.score.self')}</text><text x="470" y={185 - (series.enemy.at(-1) ?? 0) / max * 150}>{t('ui.score.enemy')}</text>{sample && <line x1={40 + sample.index / Math.max(1, series.self.length - 1) * 420} x2={40 + sample.index / Math.max(1, series.self.length - 1) * 420} y1="20" y2="170" stroke="var(--text)"/>}</svg>{sample && <output>{fmtTime(sample.timeS)} · {fmtInt(sample.self)} / {fmtInt(sample.enemy)}</output>}</figure>; }
export function ScoreScreen() { const m = useHud(), c = useCommands(), s = m.menus.score, tab = s.tab.value, rows = s.rows.value.filter(x => tab === 'overview' || x.group === tab); return <MenuShell component="ScoreScreen" title={t('ui.score.title')} footer={<><Button onClick={() => c.saveReplay()}>{t('ui.score.save')}</Button><Button onClick={() => c.watchReplay()}>{t('ui.score.watch')}</Button><Button variant="primary" onClick={() => c.rematch()}>{t('ui.score.rematch')}</Button><Button onClick={() => c.quitToMenu()}>{t('ui.score.menu')}</Button></>}><main class="score"><div class="verdict"><h2>{t(`ui.score.${s.verdict.value}`)}</h2><p>{t(s.verdict.value === 'victory' ? 'ui.score.victoryLore' : 'ui.score.defeatLore')}</p><span class="meta">{t('ui.score.duration', { time: fmtTime(s.durationS.value) })}</span></div>{s.rows.value.length > 0 && <><Tabs class="score-tabs" label={t('ui.score.title')}>{SCORE_TABS.map(x => <Tab key={x} selected={x === tab} onSelect={() => { s.tab.value = x; }}>{t(`ui.score.${x}`)}</Tab>)}</Tabs><div class="score-body"><div><table class="score-table"><thead><tr><th></th><th>{t('ui.score.self')}</th><th>{t('ui.score.enemy')}</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{t(`ui.score.${row.id}`)}</td>{[row.self, row.enemy].map((v, i) => <td key={i} class={isBetter(v, i === 0 ? row.enemy : row.self, row.lowerIsBetter) ? 'is-better' : ''}>{v === null ? '' : row.isTime ? fmtTime(v) : fmtInt(v)}</td>)}</tr>)}</tbody></table><h3>{t('ui.score.events')}</h3>{s.events.value.map((e, i) => <p key={i}>{fmtTime(e.timeS)} · {t(`ui.score.${e.kind}`)}</p>)}</div><div class="score-graphs">{s.series.value.filter(x => tab === 'overview' || tab === 'economy' && x.id === 'massIncome' || tab !== 'economy' && x.id === 'armyValue').map(x => <ScoreGraph key={x.id} series={x}/>)}</div></div></>}</main></MenuShell>; }
