import { useHud, useCommands } from '../../model/index.ts';
import { SETTING_RANGES, SETTING_CHOICES, SETTINGS_TABS } from '../../model/menus/settings.ts';
import type { SettingKey, SettingsValues } from '../../model/menus/settings.ts';
import { tDynamic as t } from '../../i18n/t.ts';
import { Button, Select, Switch, Range, Tabs, Tab, Panel, PanelHead, GRID_ROWS, keyLabel } from '../../ui/index.ts';
import { MenuShell } from '../shared/Shell.tsx';
const GROUPS = { graphics: ['preset', 'renderScale', 'shadowCascades', 'splatLayers', 'particleCap', 'bloom', 'antialias', 'frameCap', 'cameraShake'], audio: ['volMaster', 'volSfx', 'volVoice', 'volUi', 'volMusic', 'volAmbient', 'alertVoice', 'audibleStall', 'audioInBackground'], keys: ['keyScheme'], access: ['uiScale', 'teamColors', 'reducedMotion', 'statePatterns', 'iconOutline', 'alertText'], game: ['locale', 'edgePan', 'tooltips', 'pauseInBackground', 'autoSaveReplays'] } as const;
export function TeamPreview() { const m = useHud(), mode = m.menus.settings.values.value.teamColors; return <div class="team-preview" data-team-preview={mode}>{(mode === 'cvd' ? ['#0072b2', '#d7263d', '#009e73', '#cc79a7'] : mode === 'relation' ? ['#55b8ef', '#ee5555'] : ['#5da5e8', '#df5b4f', '#6ca94d', '#e2ad50']).map((color, i) => <span key={color} style={{ background: color }}>{i + 1}</span>)}</div>; }
export function Settings() {
    const m = useHud(), c = useCommands(), s = m.menus.settings, values = s.values.value, tab = s.tab.value;
    function control<K extends SettingKey>(key: K) { const label = t(`ui.settings.value.${key}`), value = values[key], range = SETTING_RANGES[key], choices = SETTING_CHOICES[key]; if (range)
        return <><Range label={label} value={value as number} min={range[0]} max={range[1]} step={range[2]} onChange={v => c.setSetting(key, v as SettingsValues[K])}/><span class="val">{value}</span></>; if (choices)
        return <Select label={label} value={String(value)} options={choices.map(v => ({ value: String(v), label: typeof v === 'number' ? String(v) : t(`ui.settings.${v}`) }))} onChange={v => c.setSetting(key, choices.find(option => String(option) === v) as SettingsValues[K])}/>; return <Switch label={label} on={Boolean(value)} onChange={v => c.setSetting(key, v as SettingsValues[K])}/>; }
    return <MenuShell title={t('ui.settings.title')} component="Settings" footer={<Button onClick={() => c.resetSettings()}>{t('ui.common.reset')}</Button>}><main class="settings"><Tabs class="vtabs" label={t('ui.settings.title')}>{SETTINGS_TABS.map(x => <Tab key={x} class="vtab" selected={tab === x} onSelect={() => { s.tab.value = x; }}>{t(`ui.settings.${x}`)}</Tab>)}</Tabs><section class="srows">{tab === 'graphics' && <div class="detect"><span>{t('ui.settings.gpu', { name: s.gpuName.value })}<br />{t(s.detectState.value === 'idle' ? 'ui.settings.detectIdle' : s.detectState.value === 'running' ? 'ui.settings.detectRunning' : 'ui.settings.detectDone', { preset: t(`ui.settings.${values.preset}`) })}</span><Button onClick={() => c.requestAutodetect()} disabled={s.detectState.value === 'running'}>{t('ui.settings.detect')}</Button></div>}{GROUPS[tab].map(key => <div key={key} class={`srow ${s.dirty.value.includes(key) ? 'is-changed' : ''}`} data-setting={key}><div class="srow__l"><b>{t(`ui.settings.value.${key}`)}</b><small>{t(tab==='graphics'?`ui.settings.help.${key}`:'ui.settings.hint')}</small></div><div class="srow__c">{control(key)}</div></div>)}{tab === 'keys' && <><p>{t('ui.settings.keyHint')}</p><div class="setting-system-keys">{[t('ui.common.key.esc'),...Array.from({length:6},(_,i)=>`F${i+1}`),t('ui.common.key.tab'),t('ui.common.key.delete'),','].map(k=><kbd key={k}>{k}</kbd>)}</div><div class="setting-keys">{GRID_ROWS.flat().map(code => <kbd key={code}>{keyLabel(code, m.locale.value === 'en' ? 'en' : 'de')}</kbd>)}</div><p>{t('ui.settings.special')}</p><Button disabled>{t('ui.settings.rebind')}</Button></>}</section><Panel class="aside-card"><PanelHead title={t('ui.settings.preview')}/><aside>{tab === 'graphics' ? <p>{t('ui.settings.quality', { n: values.particleCap, layers: values.splatLayers })}</p> : tab === 'audio' ? <Button onClick={() => c.previewAudio()}>{t('ui.settings.sample')}</Button> : tab === 'access' ? <TeamPreview /> : tab === 'keys' ? <p>{t('ui.settings.keyHint')}</p> : <p>{t('ui.settings.hint')}</p>}</aside></Panel></main></MenuShell>;
}
