import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { ClientMap } from '@faf/client';
import { expandPropFields, mapSimHash, readRtsMap, writeRtsMap } from '@faf/formats';
import { resolveMap } from '@faf/sim-host';
import { expect, test } from '@playwright/test';
import { compileMap, mapSourceFiles } from '../../../../packages/formats/scripts/mapc.ts';
import { readHeightmap } from '../../../../packages/formats/scripts/heightmap-io.ts';
import { REPO_ROOT, captureErrors, clickWorld, commitInput, dragWorld, expectNoErrors, openEditor, screenshot, worldPixel } from './support/editor.ts';

test('real editing, properties, symmetry, complete keyboard undo/redo and game-loader roundtrip', async ({ page, browserName }) => {
  const errors = captureErrors(page);
  await openEditor(page, 'hollow-ridge');
  const originalSha = await page.evaluate(() => window.__editor!.exportSha256());
  const original = await page.evaluate(() => window.__editor!.counts());
  await page.getByTestId('tool-start').click();
  await clickWorld(page, 250, 180);
  expect(await page.evaluate(() => window.__editor!.counts().starts)).toBe(original.starts + 1);
  await page.getByTestId('tool-mass').click();
  await clickWorld(page, 180, 240);
  await page.getByTestId('tool-hydro').click();
  await clickWorld(page, 300, 280);
  await page.getByTestId('tool-select').click();
  const depth = await page.evaluate(() => window.__editor!.undoDepth());
  await dragWorld(page, [180, 240], [195, 250]);
  expect(await page.evaluate(() => window.__editor!.undoDepth())).toBe(depth + 1);
  await page.getByTestId('tool-delete').click();
  await clickWorld(page, 300, 280);
  expect(await page.evaluate(() => window.__editor!.counts().hydro)).toBe(original.hydro);
  await page.getByTestId('tool-field-polygon').click();
  for (const [x, z] of [[180, 290], [215, 285], [235, 315], [215, 340], [180, 330]]) await clickWorld(page, x!, z!);
  await page.keyboard.press('Enter');
  expect(await page.evaluate(() => window.__editor!.counts().fields)).toBe(1);
  await page.getByTestId('tool-select').click();
  await clickWorld(page, 210, 315);
  await commitInput(page, 'field-name', 'Testfelsen');
  await page.getByTestId('field-kind').selectOption('rock');
  await commitInput(page, 'field-ids', 'core:rock_01:3, core:rock_02:1');
  await commitInput(page, 'field-density', '48');
  await commitInput(page, 'field-seed', '123456');
  await commitInput(page, 'field-reclaim-mass', '2.5');
  await commitInput(page, 'field-reclaim-energy', '7.25');
  // Insert a polygon edge vertex using an actual double click, then delete its handle.
  const polygon = await page.evaluate(() => window.__editor!.store.doc.peek()!.fields[0]!.shape);
  if (polygon.kind !== 'polygon') throw new Error('expected polygon');
  const a = polygon.points[0]!;
  const b = polygon.points[1]!;
  const midpoint = await worldPixel(page, (a.x + b.x) / 8192, (a.z + b.z) / 8192);
  await page.mouse.dblclick(midpoint.x, midpoint.y);
  expect(await page.evaluate(() => {
    const sh = window.__editor!.store.doc.peek()!.fields[0]!.shape;
    return sh.kind === 'polygon' ? sh.points.length : 0;
  })).toBe(6);
  const vertex = await page.evaluate(() => {
    const sh = window.__editor!.store.doc.peek()!.fields[0]!.shape;
    return sh.kind === 'polygon' ? sh.points[1]! : { x: 0, z: 0 };
  });
  await clickWorld(page, vertex.x / 4096, vertex.z / 4096);
  await page.keyboard.press('Delete');
  expect(await page.evaluate(() => {
    const sh = window.__editor!.store.doc.peek()!.fields[0]!.shape;
    return sh.kind === 'polygon' ? sh.points.length : 0;
  })).toBe(5);
  await page.getByTestId('tool-field-circle').click();
  await dragWorld(page, [130, 180], [158, 180]);
  expect(await page.evaluate(() => window.__editor!.counts().fields)).toBe(2);
  await page.getByTestId('tool-select').click();
  await clickWorld(page, 130, 180);
  await commitInput(page, 'field-radius', '28');
  await dragWorld(page, [130, 180], [140, 185]);
  const circle = await page.evaluate(() => window.__editor!.store.doc.peek()!.fields[1]!.shape);
  if (circle.kind !== 'circle') throw new Error('expected circle');
  await dragWorld(page, [(circle.x + circle.r) / 4096, circle.z / 4096], [(circle.x + circle.r) / 4096 + 12, circle.z / 4096]);
  expect(await page.evaluate(() => {
    const sh = window.__editor!.store.doc.peek()!.fields[1]!.shape;
    return sh.kind === 'circle' ? sh.r : 0;
  })).toBeGreaterThan(circle.r);
  await page.getByTestId('select-symmetry').selectOption('point');
  await page.getByTestId('btn-symmetrize').click();
  await page.getByTestId('select-symmetry').selectOption('mirrorX');
  await page.getByTestId('chk-live-symmetry').check();
  const masses = await page.evaluate(() => window.__editor!.counts().mass);
  await page.getByTestId('tool-mass').click();
  await clickWorld(page, 220, 200);
  expect(await page.evaluate(() => window.__editor!.counts().mass)).toBe(masses + 2);
  const snapshot = await page.evaluate(() => ({ depth: window.__editor!.undoDepth() }));
  const editedSha = await page.evaluate(() => window.__editor!.exportSha256());
  await screenshot(page, `edit-${browserName}`);
  await page.locator('#terrain').focus();
  for (let i = 0; i < snapshot.depth; i++) await page.keyboard.press('Control+z');
  expect(await page.evaluate(() => window.__editor!.undoDepth())).toBe(0);
  expect(await page.evaluate(() => window.__editor!.exportSha256())).toBe(originalSha);
  for (let i = 0; i < snapshot.depth; i++) await page.keyboard.press('Control+Shift+z');
  expect(await page.evaluate(() => window.__editor!.exportSha256())).toBe(editedSha);
  const downloadPromise = page.waitForEvent('download');
  await page.getByTestId('btn-save').click();
  const download = await downloadPromise;
  const exported = new Uint8Array(readFileSync((await download.path())!));
  const map = readRtsMap(exported);
  expect(writeRtsMap(ClientMap.fromBytes(exported).map)).toEqual(exported);
  expect(writeRtsMap(resolveMap(exported))).toEqual(exported);
  expect(mapSimHash(map) >>> 0).toBe(await page.evaluate(() => window.__editor!.mapSimHash()));
  expect(expandPropFields(map).length).toBe(await page.evaluate(() => window.__editor!.counts().expandedProps));
  const rock = map.propFields!.find((f) => f.name === 'Testfelsen')!;
  expect(rock).toMatchObject({ kind: 'rock', densityPerKWu2: 48, seed: 123456, reclaimMassMilli: 2500, reclaimEnergyMilli: 7250 });
  expect(rock.entries).toEqual([{ id: 'core:rock_01', weight: 3 }, { id: 'core:rock_02', weight: 1 }]);
  const jsonPromise = page.waitForEvent('download');
  await page.getByTestId('btn-export-markers').click();
  const json = JSON.parse(readFileSync((await (await jsonPromise).path())!, 'utf8')) as { mass: unknown[]; hydro: unknown[]; starts: unknown[]; propFields: unknown[] };
  expect(json.mass.length).toBe(map.meta.spots.filter((s) => s.kind === 'mass').length);
  expect(json.propFields.length).toBe(map.propFields!.length);
  const sources = mapSourceFiles(resolve(REPO_ROOT, 'content/maps/src/hollow-ridge'));
  const compiled = compileMap({ heightmap: readHeightmap(sources.heightmap), markers: json });
  expect(compiled.meta.starts).toEqual(map.meta.starts);
  expect(compiled.meta.spots).toEqual([...map.meta.spots.filter((s) => s.kind === 'mass'), ...map.meta.spots.filter((s) => s.kind === 'hydro')]);
  expect(compiled.propFields).toEqual(map.propFields);
  expect(new Set(map.propFields!.map((f) => f.shape.kind))).toEqual(new Set(['circle', 'polygon']));
  expectNoErrors(errors);
});

test('help is readable at both required viewport sizes', async ({ page, browserName }) => {
  await openEditor(page, 'tessera');
  for (const [width, height] of [[1280, 720], [1920, 1080]]) {
    await page.setViewportSize({ width: width!, height: height! });
    await page.keyboard.press('?');
    await expect(page.getByTestId('help-overlay')).toBeVisible();
    await screenshot(page, `help-${width}-${browserName}`);
    await page.keyboard.press('Escape');
  }
});
