/**
 * Stateless GPU particle system (PLAN §3.7 "zustandsloser Spawn-Ring (64k, Cap nach Preset),
 * f(t−t0) im VS, Kurven-LUT, defineEffect-Daten, Prioritäten").
 *
 * - One instance vertex buffer holds `capacity` spawn records (record.ts, 32 B) plus a CPU mirror.
 *   Records are written once at spawn and never touched again: the vertex shader evaluates each
 *   particle as f(now − t0). Per frame only the NEW records are uploaded (≤ 2 writeBuffer when the
 *   range wraps around the ring end); the restore callback re-uploads the whole mirror, so particles
 *   keep flying after a context loss.
 * - The live window [tail, head) of the ring is drawn in one instanced draw (two when it wraps).
 *   Expired particles inside the window are degenerated by the vertex shader; the window's tail
 *   follows the expired slots. A long-lived particle at the tail would keep the window (and the
 *   vertex work) open far beyond the cap, so update() bounds it actively: while the window exceeds
 *   WINDOW_FACTOR · max(alive, cap), live tail records are relocated to the head. Records are
 *   stateless (image = f(now − t0), t0/seed travel with the record), so a relocated particle looks
 *   the same; only its draw order changes. Cost: one extra upload of the relocated records.
 * - Alive counting without scanning: per-slot expiry (Float64Array) + a histogram of expiries in
 *   1/64 s buckets. A particle counts as alive until the end of its expiry bucket.
 * - Caps/priorities: priority 0 always spawns, priority 1 while alive < cap, priority 2 while
 *   alive < 0.75·cap; priority-2 bursts outside the frustum or tiny on screen are culled, small
 *   ones thinned. When the ring is full, the oldest slot is overwritten – unless it holds a live
 *   priority-0 particle: that one moves into the oldest priority-1/2 (or expired) slot instead, so
 *   priority 0 is only lost when nothing else is left.
 * - Continuous emitters (≤ 1024): per-layer accumulators with sub-frame spawn times (no pulsing).
 *
 * Hot paths (update, encode, spawn, emitters) do not allocate once warm: doubles never cross a
 * (possibly non-inlined) call boundary – they travel through Float64Array scratch slots – and the
 * hash/half helpers used there return small integers.
 */
import type { BindGroupH, BufH, GpuDevice, PassEncoder, PipeH, RenderPreset, RenderPresetName, RtsCamera, TexH, VertexStreamBinding } from '@faf/render';
import { RENDER_PRESETS, SLOT_FRAME } from '@faf/render';
import { FX_TIME_WRAP_S, SLOT_FX_VIEW, UNIT_FX_CURVE_LUT, UNIT_FX_PARTICLE_LAYERS } from '../core/slots.ts';
import type { FxBindings } from '../core/view.ts';
import { fxSharedBufferBindings } from '../core/view.ts';
import type { EffectDefCompiled, EffectLibrary } from '../effects/compile.ts';
import {
  L_COUNT_MAX,
  L_COUNT_MIN,
  L_DELAY_MAX,
  L_DELAY_MIN,
  L_LIFE_MAX,
  L_LIFE_MIN,
  L_MOTION,
  L_PRIORITY,
  L_RATE,
  LAYER_STRIDE,
  LAYER_TEXELS,
} from '../effects/compile.ts';
import { MAX_EFFECT_LAYERS } from '../effects/define.ts';
import { PARTICLE_RECORD_STRIDE, PARTICLE_STREAM_LAYOUT, REC_TINT, halfBitsAt, recordViews } from './record.ts';
import type { RecordViews } from './record.ts';
import { PARTICLE_FS, PARTICLE_VS } from './shaders.ts';

/** Default ring size (PLAN §3.7: 64k). */
export const PARTICLE_RING_CAPACITY = 65536;
/** Maximum concurrent continuous emitters. */
export const MAX_PARTICLE_EMITTERS = 1024;
/** Expiry histogram resolution (s) and size (buckets; covers 128 s > max particle age 40 s + slack). */
export const EXPIRY_BUCKET_S = 1 / 64;
const BUCKETS = 8192;
const BUCKET_MASK = BUCKETS - 1;
const BUCKETS_PER_S = 64;
/** The drawn window is kept ≤ WINDOW_FACTOR · max(alive, cap) (at least MIN_WINDOW, at most the ring). */
export const WINDOW_FACTOR = 1.5;
/** Lower bound of the window limit (avoids relocation churn for tiny particle counts). */
export const MIN_WINDOW = 256;
/** Most tail slots one update() examines for window compaction (bounds the CPU work per frame). */
export const MAX_COMPACT_PER_UPDATE = 16384;
/** Most slots a full-ring eviction scans for a priority-1/2 victim before sacrificing priority 0. */
export const EVICT_SCAN_MAX = 4096;
/** Priority 2 spawns only while alive < PRIO2_CAP_FRACTION · cap. */
export const PRIO2_CAP_FRACTION = 0.75;
/** Priority-2 bursts whose bounds sphere covers less than this many pixels (radius) are culled. */
export const CULL_RADIUS_PX = 1.5;
/** Below this on-screen radius (px) priority-2 bursts are thinned proportionally. */
export const THIN_RADIUS_PX = 8;
/** Largest time step used for continuous emission (avoids bursts after a stall). */
export const MAX_EMIT_DT_S = 0.25;

const EMITTER_BITS = 10;
const EMITTER_MASK = (1 << EMITTER_BITS) - 1;
/** Visibility factor fixed point: 1024 = fully visible. */
const VIS_ONE = 1024;

// Float64 scratch slots (doubles never cross call boundaries in hot paths, see the module comment).
const T_NOW = 0; // current particle clock (s)
const T_DT = 1; // emission step of this update (s)
const T_T0 = 2; // absolute spawn time of the records being written (s)
const T_RADIUS = 3; // bounds radius for visibility() (WU)
const T_START = 4; // start of the emission interval of this update (s)
const V_DIR = 0; // 0..2 emission axis (unnormalized)
const V_SCALE = 3;
const V_TGT = 4; // 4..6 stream target delta (WU)

/** Particle ring cap of a render preset (RENDER_PRESETS[p].caps.particles: low 8192 … ultra 65536). */
export function particleCapForPreset(p: RenderPresetName | RenderPreset): number {
  return typeof p === 'string' ? RENDER_PRESETS[p].caps.particles : p.caps.particles;
}

/**
 * Low 16 bits of `fxHash32(a, b, c)` (effects/random.ts), computed inline so the result is always a
 * small integer (no HeapNumber for u32 results ≥ 2^30). Parity with fxHash32 is tested.
 */
export function hashLo16(a: number, b: number, c: number): number {
  let h = (a + 0x9e3779b9) | 0;
  h ^= h >>> 16;
  h = Math.imul(h, 0x85ebca6b);
  h ^= h >>> 13;
  h = Math.imul(h, 0xc2b2ae35);
  h ^= h >>> 16;
  h ^= (b + 0x7f4a7c15) | 0;
  h ^= h >>> 16;
  h = Math.imul(h, 0x85ebca6b);
  h ^= h >>> 13;
  h = Math.imul(h, 0xc2b2ae35);
  h ^= h >>> 16;
  h ^= (c + 0x94d049bb) | 0;
  h ^= h >>> 16;
  h = Math.imul(h, 0x85ebca6b);
  h ^= h >>> 13;
  h = Math.imul(h, 0xc2b2ae35);
  h ^= h >>> 16;
  return h & 0xffff;
}

/** `fxHash32(a, b, c) >>> 8` (24 bits, always a small integer). */
export function hashHi24(a: number, b: number, c: number): number {
  let h = (a + 0x9e3779b9) | 0;
  h ^= h >>> 16;
  h = Math.imul(h, 0x85ebca6b);
  h ^= h >>> 13;
  h = Math.imul(h, 0xc2b2ae35);
  h ^= h >>> 16;
  h ^= (b + 0x7f4a7c15) | 0;
  h ^= h >>> 16;
  h = Math.imul(h, 0x85ebca6b);
  h ^= h >>> 13;
  h = Math.imul(h, 0xc2b2ae35);
  h ^= h >>> 16;
  h ^= (c + 0x94d049bb) | 0;
  h ^= h >>> 16;
  h = Math.imul(h, 0x85ebca6b);
  h ^= h >>> 13;
  h = Math.imul(h, 0xc2b2ae35);
  h ^= h >>> 16;
  return h >>> 8;
}

export interface ParticleSystemOptions {
  /** Ring size in records (default 65536). */
  readonly capacity?: number;
  /** Preset cap (`particleCapForPreset`), ≤ capacity. */
  readonly cap: number;
  /** Called by `spawn()` for effects with a `shake` definition (fx-lab: CameraShake.addFromEffect). */
  readonly onShake?: (effect: EffectDefCompiled, posRaw: Int32Array | readonly number[], tS: number) => void;
}

export interface ParticleSpawnOptions {
  /** Emission axis (unit vector, default +y). */
  readonly dir?: ArrayLike<number>;
  /** Effect scale (size, speed, emit radius, stream wave), default 1. */
  readonly scale?: number;
  /** Seed of the burst (default: internal deterministic counter). */
  readonly seed?: number;
  /** Spawn tint 0xRRGGBB for layers with tint 'spawn' (default 0xFFFFFF). */
  readonly tint?: number;
  /** Stream target (raw Q20.12) for layers with motion 'stream' (default = origin). */
  readonly targetRaw?: ArrayLike<number>;
}

export interface ParticleStats {
  /** Particles spawned and not yet expired (1/64 s resolution), including pending delays. */
  alive: number;
  cap: number;
  capacity: number;
  /** Particles written since the last encode(). */
  spawnedFrame: number;
  /** Requested particles per priority (cumulative). */
  requested: [number, number, number];
  /** Particles rejected by the cap per priority (cumulative). */
  dropped: [number, number, number];
  /** Priority-2 particles culled or thinned by visibility (cumulative). */
  culled: number;
  /** Bytes uploaded since the last encode(). */
  uploadBytesFrame: number;
  /** Active continuous emitters. */
  emitters: number;
  /** Still-alive particles overwritten because the ring was full, per priority (cumulative). */
  overwritten: [number, number, number];
  /** Records in the drawn window [tail, head) = instances the particle VS runs for. */
  window: number;
  /** Current bound of the window: WINDOW_FACTOR · max(alive, cap), clamped to [MIN_WINDOW, capacity]. */
  windowLimit: number;
  /** Live records moved from the tail to the head to keep the window bounded (cumulative). */
  relocated: number;
  /** Draw calls of the last encode(). */
  draws: number;
}

export class ParticleSystem {
  readonly capacity: number;
  readonly lib: EffectLibrary;
  private cap: number;
  private readonly onShake: ParticleSystemOptions['onShake'];

  // ---- ring ----
  private readonly views: RecordViews;
  private readonly ringBuf: BufH;
  /** Absolute expiry time (s) per slot; relative lifetime (delay + life) while the slot is pending. */
  private readonly expiry: Float64Array;
  private head = 0;
  private tail = 0;
  /** First slot whose t0 is not assigned yet (spawned before this frame's update). */
  private pendingStart = 0;
  /** First slot not uploaded yet. */
  private uploaded = 0;
  /** Already uploaded positions [dirtyLo, dirtyHi) rewritten by full-ring evictions (empty: lo ≥ hi). */
  private dirtyLo = 0;
  private dirtyHi = 0;
  /** Full-ring eviction: positions in [tail, evictScan) were live priority-0 slots when scanned. */
  private evictScan = 0;

  // ---- alive histogram ----
  private readonly hist = new Int32Array(BUCKETS);
  private histAlive = 0;
  private curBucket = 0;

  // ---- time / frame state ----
  /** Float64 scratch: T_NOW, T_DT, T_T0, T_RADIUS, T_START. */
  private readonly tm = new Float64Array(5);
  private hasTime = false;
  private frameOpen = false;
  private frameClosed = true;
  private autoSeed = 0;

  // ---- camera (culling) ----
  /** 6 frustum planes (nx, ny, nz, d) relative to camInt in WU: left, right, bottom, top, near, far. */
  private readonly planes = new Float64Array(24);
  private readonly camInt = new Int32Array(3);
  /** [0] = pixels per WU at distance 1. */
  private readonly pxPerWu = new Float64Array(1);
  private hasCamera = false;

  // ---- layer / effect caches ----
  private readonly lifeMin: Float64Array;
  private readonly lifeRange: Float64Array;
  private readonly delayMin: Float64Array;
  private readonly delayRange: Float64Array;
  private readonly prio: Uint8Array;
  private readonly isStream: Uint8Array;
  private readonly rate: Float64Array;
  private readonly countMin: Int32Array;
  private readonly countMax: Int32Array;

  // ---- emitters ----
  private readonly emActive = new Uint8Array(MAX_PARTICLE_EMITTERS);
  private readonly emGen = new Uint32Array(MAX_PARTICLE_EMITTERS);
  private readonly emEffect = new Int32Array(MAX_PARTICLE_EMITTERS);
  private readonly emPos = new Int32Array(MAX_PARTICLE_EMITTERS * 3);
  private readonly emTarget = new Int32Array(MAX_PARTICLE_EMITTERS * 3);
  private readonly emDir = new Float64Array(MAX_PARTICLE_EMITTERS * 3);
  private readonly emScale = new Float64Array(MAX_PARTICLE_EMITTERS);
  private readonly emRate = new Float64Array(MAX_PARTICLE_EMITTERS);
  private readonly emTint = new Int32Array(MAX_PARTICLE_EMITTERS);
  private readonly emSeed = new Uint32Array(MAX_PARTICLE_EMITTERS);
  private readonly emCounter = new Uint32Array(MAX_PARTICLE_EMITTERS);
  /** Encoded f16 vectors per emitter: ballistic (axis, scale) and stream (target delta, scale). */
  private readonly emHalfB = new Uint16Array(MAX_PARTICLE_EMITTERS * 4);
  private readonly emHalfS = new Uint16Array(MAX_PARTICLE_EMITTERS * 4);
  private readonly emAccum = new Float64Array(MAX_PARTICLE_EMITTERS * MAX_EFFECT_LAYERS);
  /** Dense list of active emitter indices + position of each index in it. */
  private readonly emList = new Int32Array(MAX_PARTICLE_EMITTERS);
  private readonly emListPos = new Int32Array(MAX_PARTICLE_EMITTERS);
  private emCount = 0;
  private readonly emFree = new Int32Array(MAX_PARTICLE_EMITTERS);
  private emFreeCount = MAX_PARTICLE_EMITTERS;

  // ---- GPU ----
  private readonly dev: GpuDevice;
  private readonly lutTex: TexH;
  private readonly layerTex: TexH;
  private readonly pipeline: PipeH;
  private readonly group: BindGroupH;
  private readonly streams: VertexStreamBinding[];
  private destroyed = false;

  // ---- scratch ----
  /** V_DIR, V_SCALE, V_TGT inputs of encodeVectors(). */
  private readonly vin = new Float64Array(8);
  private readonly halfB = new Uint16Array(4);
  private readonly halfS = new Uint16Array(4);
  private readonly shakePos = new Int32Array(3);
  private readonly st: ParticleStats;

  constructor(dev: GpuDevice, bindings: FxBindings, lib: EffectLibrary, opts: ParticleSystemOptions) {
    const capacity = opts.capacity ?? PARTICLE_RING_CAPACITY;
    if (!Number.isInteger(capacity) || capacity < 1 || capacity > 1 << 20) {
      throw new RangeError(`ParticleSystem: capacity ${capacity} outside [1, 2^20]`);
    }
    if (lib.layerCount < 1) throw new Error('ParticleSystem: effect library has no layers');
    this.dev = dev;
    this.lib = lib;
    this.capacity = capacity;
    this.cap = this.checkCap(opts.cap);
    this.onShake = opts.onShake;

    const n = lib.layerCount;
    this.lifeMin = new Float64Array(n);
    this.lifeRange = new Float64Array(n);
    this.delayMin = new Float64Array(n);
    this.delayRange = new Float64Array(n);
    this.prio = new Uint8Array(n);
    this.isStream = new Uint8Array(n);
    this.rate = new Float64Array(n);
    this.countMin = new Int32Array(n);
    this.countMax = new Int32Array(n);
    const L = lib.layers;
    for (let i = 0; i < n; i++) {
      const o = i * LAYER_STRIDE;
      // Same f32 values the shader reads from the layer texture.
      this.lifeMin[i] = L[o + L_LIFE_MIN]!;
      this.lifeRange[i] = L[o + L_LIFE_MAX]! - L[o + L_LIFE_MIN]!;
      this.delayMin[i] = L[o + L_DELAY_MIN]!;
      this.delayRange[i] = L[o + L_DELAY_MAX]! - L[o + L_DELAY_MIN]!;
      this.prio[i] = L[o + L_PRIORITY]!;
      this.isStream[i] = L[o + L_MOTION]! > 0.5 ? 1 : 0;
      this.rate[i] = L[o + L_RATE]!;
      this.countMin[i] = L[o + L_COUNT_MIN]!;
      this.countMax[i] = L[o + L_COUNT_MAX]!;
    }
    for (const e of lib.effects) {
      if (e.layerCount > MAX_EFFECT_LAYERS) throw new Error(`ParticleSystem: effect ${e.id} has > ${MAX_EFFECT_LAYERS} layers`);
    }

    this.views = recordViews(new ArrayBuffer(capacity * PARTICLE_RECORD_STRIDE));
    this.expiry = new Float64Array(capacity);
    for (let i = 0; i < MAX_PARTICLE_EMITTERS; i++) this.emFree[i] = MAX_PARTICLE_EMITTERS - 1 - i;

    this.ringBuf = dev.createBuffer({
      label: 'fx.particles.ring',
      usage: 'vertex',
      size: capacity * PARTICLE_RECORD_STRIDE,
      dynamic: true,
      // Whole mirror: records are immutable after spawn, so this restores every live particle.
      restore: (h) => dev.writeBuffer(h, 0, this.views.u8),
    });
    const lut = lib.lut;
    this.lutTex = dev.createTexture({
      label: 'fx.particles.lut',
      width: lut.width,
      height: lut.height,
      format: 'rgba16f',
      filter: 'linear',
      wrap: 'clamp',
      restore: (h) => dev.writeTexture(h, { x: 0, y: 0, width: lut.width, height: lut.height }, lut.data),
    });
    dev.writeTexture(this.lutTex, { x: 0, y: 0, width: lut.width, height: lut.height }, lut.data);
    const layerData = lib.layers.subarray(0, n * LAYER_STRIDE);
    this.layerTex = dev.createTexture({
      label: 'fx.particles.layers',
      width: LAYER_TEXELS,
      height: n,
      format: 'rgba32f',
      filter: 'nearest',
      wrap: 'clamp',
      restore: (h) => dev.writeTexture(h, { x: 0, y: 0, width: LAYER_TEXELS, height: n }, layerData),
    });
    dev.writeTexture(this.layerTex, { x: 0, y: 0, width: LAYER_TEXELS, height: n }, layerData);
    this.pipeline = dev.createPipeline({
      label: 'fx.particles',
      vertex: PARTICLE_VS,
      fragment: PARTICLE_FS,
      streams: [PARTICLE_STREAM_LAYOUT],
      uniformBlocks: [
        { name: 'Frame', slot: SLOT_FRAME },
        { name: 'FxView', slot: SLOT_FX_VIEW },
      ],
      samplers: [
        { name: 'u_fxCurveLut', unit: UNIT_FX_CURVE_LUT },
        { name: 'u_fxParticleLayers', unit: UNIT_FX_PARTICLE_LAYERS },
      ],
      primitive: 'triangle-strip',
      cullMode: 'none',
      depthTest: true,
      depthWrite: false,
      blend: 'premultiplied',
    });
    this.group = dev.createBindGroup({
      label: 'fx.particles',
      buffers: fxSharedBufferBindings(bindings),
      textures: [
        { unit: UNIT_FX_CURVE_LUT, texture: this.lutTex },
        { unit: UNIT_FX_PARTICLE_LAYERS, texture: this.layerTex },
      ],
    });
    this.streams = [{ buffer: this.ringBuf, offset: 0 }];
    this.st = {
      alive: 0,
      cap: this.cap,
      capacity,
      spawnedFrame: 0,
      requested: [0, 0, 0],
      dropped: [0, 0, 0],
      culled: 0,
      uploadBytesFrame: 0,
      emitters: 0,
      overwritten: [0, 0, 0],
      window: 0,
      windowLimit: 0,
      relocated: 0,
      draws: 0,
    };
  }

  private checkCap(n: number): number {
    if (!Number.isInteger(n) || n < 0 || n > this.capacity) {
      throw new RangeError(`ParticleSystem: cap ${n} outside [0, ${this.capacity}]`);
    }
    return n;
  }

  /** Changes the preset cap (0 ≤ n ≤ capacity). Particles above the new cap live out their life. */
  setCap(n: number): void {
    this.cap = this.checkCap(n);
  }

  /** Live counters (the same object every call, updated in place). */
  get stats(): Readonly<ParticleStats> {
    const s = this.st;
    s.alive = this.aliveTotal();
    s.cap = this.cap;
    s.emitters = this.emCount;
    s.window = this.head - this.tail;
    s.windowLimit = this.windowLimit();
    return s;
  }

  /** Current particle clock (s) – the `nowS` of the last update(). */
  get timeS(): number {
    return this.tm[T_NOW]!;
  }

  /** CPU mirror of the ring (tests, debugging). */
  get records(): RecordViews {
    return this.views;
  }

  /** Ring positions of the drawn window: slots [tail, head) modulo capacity (tests). */
  get windowRange(): { readonly tail: number; readonly head: number } {
    return { tail: this.tail, head: this.head };
  }

  /** Absolute expiry time of ring slot `slot` (tests). */
  expiryOf(slot: number): number {
    return this.expiry[slot]!;
  }

  private aliveTotal(): number {
    return this.histAlive + (this.head - this.pendingStart);
  }

  /** WINDOW_FACTOR · max(alive, cap), clamped to [MIN_WINDOW, capacity]. */
  private windowLimit(): number {
    const a = this.aliveTotal();
    const m = a > this.cap ? a : this.cap;
    const l = Math.floor(WINDOW_FACTOR * m);
    const lo = l < MIN_WINDOW ? MIN_WINDOW : l;
    return lo > this.capacity ? this.capacity : lo;
  }

  private openFrame(): void {
    if (!this.frameClosed) return;
    this.frameClosed = false;
    this.st.spawnedFrame = 0;
    this.st.uploadBytesFrame = 0;
  }

  // ------------------------------------------------------------------------------------ spawning

  /**
   * Spawns a burst of effect `effectIdx` at `posRaw` (raw Q20.12). Before `update()` of a frame the
   * records are pending and get this frame's time in `update()`; between `update()` and `encode()`
   * they get the current time directly. Either way they are uploaded and drawn in the same frame.
   * Returns the number of particles written.
   */
  spawn(effectIdx: number, posRaw: ArrayLike<number>, o?: ParticleSpawnOptions): number {
    const eff = this.lib.effects[effectIdx];
    if (eff === undefined) throw new RangeError(`ParticleSystem.spawn: unknown effect index ${effectIdx}`);
    this.openFrame();
    const seed = o?.seed;
    // 24-bit seed bases stay small integers (no boxing).
    const seedBase = seed !== undefined ? hashHi24(seed >>> 0, effectIdx, 0x5eed) : hashHi24(this.autoSeed++ & 0x3fffffff, effectIdx, 0xa070);
    const px = posRaw[0]! | 0;
    const py = posRaw[1]! | 0;
    const pz = posRaw[2]! | 0;
    const vin = this.vin;
    const dir = o?.dir;
    vin[V_DIR] = dir !== undefined ? dir[0]! : 0;
    vin[V_DIR + 1] = dir !== undefined ? dir[1]! : 1;
    vin[V_DIR + 2] = dir !== undefined ? dir[2]! : 0;
    vin[V_SCALE] = o?.scale ?? 1;
    const tgt = o?.targetRaw;
    vin[V_TGT] = tgt !== undefined ? (tgt[0]! - px) / 4096 : 0;
    vin[V_TGT + 1] = tgt !== undefined ? (tgt[1]! - py) / 4096 : 0;
    vin[V_TGT + 2] = tgt !== undefined ? (tgt[2]! - pz) / 4096 : 0;
    this.encodeVectors(this.halfB, this.halfS, 0);
    const tint = (o?.tint ?? 0xffffff) & 0xffffff;
    this.tm[T_RADIUS] = eff.boundsWu * vin[V_SCALE]!;
    const vis = this.visibility(px, py, pz);
    const final = this.frameOpen;
    this.tm[T_T0] = this.tm[T_NOW]!;
    let total = 0;
    for (let j = 0; j < eff.layerCount; j++) {
      const li = eff.firstLayer + j;
      const cMin = this.countMin[li]!;
      const cMax = this.countMax[li]!;
      if (cMax <= 0) continue;
      const n = cMin + Math.floor((hashHi24(seedBase, li, 0xc0) / 16777216) * (cMax - cMin + 1));
      const allowed = this.admit(li, n, vis);
      const lseed = hashLo16(seedBase, li, 0x51);
      for (let i = 0; i < allowed; i++) {
        this.writeParticle(li, (lseed + i) & 0xffff, px, py, pz, final, tint, this.halfB, this.halfS, 0);
      }
      total += allowed;
    }
    if (eff.shake !== null && this.onShake !== undefined) {
      const sp = this.shakePos;
      sp[0] = px;
      sp[1] = py;
      sp[2] = pz;
      this.onShake(eff, sp, this.tm[T_NOW]!);
    }
    return total;
  }

  /**
   * Applies visibility culling (priority 2) and the cap rules to a request of `n` particles of layer
   * `li`; updates requested/dropped/culled and returns how many may be written. `vis` is the
   * fixed-point visibility factor of {@link visibility}.
   */
  private admit(li: number, n: number, vis: number): number {
    if (n <= 0) return 0;
    const p = this.prio[li]!;
    const st = this.st;
    st.requested[p]! += n;
    if (p === 2 && vis < VIS_ONE) {
      const keep = vis <= 0 ? 0 : (n * vis + (VIS_ONE >> 1)) >> 10;
      st.culled += n - keep;
      n = keep;
      if (n === 0) return 0;
    }
    if (p === 0) return n;
    const limit = p === 1 ? this.cap : Math.floor(PRIO2_CAP_FRACTION * this.cap);
    const room = limit - this.aliveTotal();
    const allowed = room <= 0 ? 0 : room < n ? room : n;
    st.dropped[p]! += n - allowed;
    return allowed;
  }

  /**
   * Visibility of a burst at raw position (x, y, z) with bounds radius tm[T_RADIUS] (WU), as fixed
   * point: VIS_ONE = fully visible, 0 = cull, in between = thinning factor for priority-2
   * particles (on-screen radius below THIN_RADIUS_PX). Without a camera (no update yet) everything
   * is visible.
   */
  private visibility(x: number, y: number, z: number): number {
    if (!this.hasCamera) return VIS_ONE;
    const r = this.tm[T_RADIUS]!;
    const rx = (x - this.camInt[0]!) / 4096;
    const ry = (y - this.camInt[1]!) / 4096;
    const rz = (z - this.camInt[2]!) / 4096;
    const p = this.planes;
    for (let i = 0; i < 24; i += 4) {
      if (p[i]! * rx + p[i + 1]! * ry + p[i + 2]! * rz + p[i + 3]! < -r) return 0;
    }
    const dist = Math.sqrt(rx * rx + ry * ry + rz * rz);
    if (dist <= r) return VIS_ONE;
    const px = (r * this.pxPerWu[0]!) / dist;
    if (px < CULL_RADIUS_PX) return 0;
    if (px < THIN_RADIUS_PX) return Math.floor((px / THIN_RADIUS_PX) * VIS_ONE);
    return VIS_ONE;
  }

  /**
   * Encodes the vectors in `vin` into f16 bit patterns: `hb` (ballistic: unit axis + scale) and
   * `hs` (stream: target delta in WU + scale), both at offset `o`.
   */
  private encodeVectors(hb: Uint16Array, hs: Uint16Array, o: number): void {
    const v = this.vin;
    const l = Math.sqrt(v[0]! * v[0]! + v[1]! * v[1]! + v[2]! * v[2]!);
    if (l > 1e-9) {
      v[0] = v[0]! / l;
      v[1] = v[1]! / l;
      v[2] = v[2]! / l;
    } else {
      v[0] = 0;
      v[1] = 1;
      v[2] = 0;
    }
    hb[o] = halfBitsAt(v, V_DIR);
    hb[o + 1] = halfBitsAt(v, V_DIR + 1);
    hb[o + 2] = halfBitsAt(v, V_DIR + 2);
    const sc = halfBitsAt(v, V_SCALE);
    hb[o + 3] = sc;
    hs[o] = halfBitsAt(v, V_TGT);
    hs[o + 1] = halfBitsAt(v, V_TGT + 1);
    hs[o + 2] = halfBitsAt(v, V_TGT + 2);
    hs[o + 3] = sc;
  }

  /**
   * Writes one record at the ring head (evicting the oldest slot when the ring is full). The spawn
   * time is tm[T_T0]; vectors come from `hb`/`hs` at offset `ho` (see encodeVectors).
   */
  private writeParticle(
    li: number,
    seed: number,
    px: number,
    py: number,
    pz: number,
    final: boolean,
    tint: number,
    hb: Uint16Array,
    hs: Uint16Array,
    ho: number,
  ): void {
    if (this.head - this.tail >= this.capacity) this.evictOne();
    const slot = this.head % this.capacity;
    const t0Abs = this.tm[T_T0]!;
    let t0w = t0Abs % FX_TIME_WRAP_S; // = wrapFxTime(t0Abs)
    if (t0w < 0) t0w += FX_TIME_WRAP_S;
    const hv = this.isStream[li] === 1 ? hs : hb;
    const v = this.views;
    const w = slot * 8; // 32-bit words
    v.i32[w] = px;
    v.i32[w + 1] = py;
    v.i32[w + 2] = pz;
    v.f32[w + 3] = final ? t0w : 0;
    const h = slot * 16; // 16-bit words
    v.u16[h + 8] = hv[ho]!;
    v.u16[h + 9] = hv[ho + 1]!;
    v.u16[h + 10] = hv[ho + 2]!;
    v.u16[h + 11] = hv[ho + 3]!;
    v.u16[h + 12] = li;
    v.u16[h + 13] = seed;
    const b = slot * PARTICLE_RECORD_STRIDE + REC_TINT;
    v.u8[b] = (tint >>> 16) & 255;
    v.u8[b + 1] = (tint >>> 8) & 255;
    v.u8[b + 2] = tint & 255;
    v.u8[b + 3] = 255;
    // Same randoms as the shader: uLife = lo(h0), uDelay = lo(h4).
    const uLife = hashLo16(seed, li, 0) / 65536;
    const uDelay = hashLo16(seed, li, 4) / 65536;
    const rel = this.delayMin[li]! + this.delayRange[li]! * uDelay + this.lifeMin[li]! + this.lifeRange[li]! * uLife;
    if (final) {
      const exp = t0Abs + rel;
      this.expiry[slot] = exp;
      const bk = Math.floor(exp * BUCKETS_PER_S);
      // Already expired (sub-frame emission at the end of its life) → not counted.
      if (bk >= this.curBucket) {
        this.hist[bk & BUCKET_MASK]!++;
        this.histAlive++;
      }
    } else {
      this.expiry[slot] = rel;
    }
    this.head++;
    // Final records only appear while no record is pending (pending records form a suffix).
    if (final) this.pendingStart = this.head;
    this.st.spawnedFrame++;
  }

  /** Priority of the record in ring slot `slot` (from its layer index). */
  private prioOfSlot(slot: number): number {
    return this.prio[this.views.u16[slot * 16 + 12]!]!;
  }

  /**
   * Drops the particle in ring slot `slot` (final: absolute expiry, else pending): removes it from
   * the alive histogram and counts it as overwritten if it was still alive.
   */
  private dropSlot(slot: number, final: boolean): void {
    const p = this.prioOfSlot(slot);
    if (final) {
      const b = Math.floor(this.expiry[slot]! * BUCKETS_PER_S);
      if (b >= this.curBucket) {
        this.hist[b & BUCKET_MASK]!--;
        this.histAlive--;
        this.st.overwritten[p]!++;
      }
    } else {
      this.st.overwritten[p]!++;
    }
  }

  /**
   * Frees the oldest ring position (the ring is full: head − tail = capacity). A live priority-0
   * particle at the tail is not lost while a priority-1/2 or expired slot of the same kind (final or
   * pending) exists within EVICT_SCAN_MAX slots: it is copied over that victim instead.
   */
  private evictOne(): void {
    const cap = this.capacity;
    const t = this.tail;
    const slot = t % cap;
    const final = t < this.pendingStart;
    const end = final ? this.pendingStart : this.head;
    const now = this.tm[T_NOW]!;
    this.tail = t + 1;
    if (!final) this.pendingStart = this.tail;
    // Expired: nothing is lost (the histogram drops it with its bucket).
    if (final && this.expiry[slot]! <= now) return;
    if (this.prioOfSlot(slot) !== 0) {
      this.dropSlot(slot, final);
      return;
    }
    let v = this.evictScan > t + 1 ? this.evictScan : t + 1;
    const scanEnd = t + 1 + EVICT_SCAN_MAX < end ? t + 1 + EVICT_SCAN_MAX : end;
    for (; v < scanEnd; v++) {
      const vs = v % cap;
      if (final && this.expiry[vs]! <= now) break;
      if (this.prioOfSlot(vs) !== 0) break;
    }
    if (v >= scanEnd) {
      // Only priority 0 left: the oldest one goes.
      this.evictScan = v;
      this.dropSlot(slot, final);
      return;
    }
    const vs = v % cap;
    if (!(final && this.expiry[vs]! <= now)) this.dropSlot(vs, final);
    const S = PARTICLE_RECORD_STRIDE;
    this.views.u8.copyWithin(vs * S, slot * S, slot * S + S);
    this.expiry[vs] = this.expiry[slot]!;
    this.evictScan = v + 1;
    if (v < this.uploaded) {
      if (this.dirtyLo >= this.dirtyHi) {
        this.dirtyLo = v;
        this.dirtyHi = v + 1;
      } else {
        if (v < this.dirtyLo) this.dirtyLo = v;
        if (v + 1 > this.dirtyHi) this.dirtyHi = v + 1;
      }
    }
  }

  /**
   * Keeps the drawn window ≤ windowLimit(): walks the tail, drops expired records and relocates live
   * ones to the head (byte copy – t0, seed and expiry stay, so the particle's image is unchanged).
   * Runs only while no record is pending (relocated records are final and must not precede pending
   * ones).
   */
  private compact(): void {
    if (this.pendingStart !== this.head) return;
    const limit = this.windowLimit();
    if (this.head - this.tail <= limit) return;
    const cap = this.capacity;
    const now = this.tm[T_NOW]!;
    const S = PARTICLE_RECORD_STRIDE;
    const u8 = this.views.u8;
    let budget = MAX_COMPACT_PER_UPDATE;
    const w0 = this.head - this.tail;
    if (budget > w0) budget = w0;
    while (this.head - this.tail > limit && budget > 0) {
      budget--;
      const src = this.tail % cap;
      if (this.expiry[src]! > now) {
        const dst = this.head % cap;
        if (dst !== src) {
          u8.copyWithin(dst * S, src * S, src * S + S);
          this.expiry[dst] = this.expiry[src]!;
        }
        this.head++;
        this.st.relocated++;
      }
      this.tail++;
    }
    this.pendingStart = this.head;
  }

  // ------------------------------------------------------------------------------------ emitters

  /**
   * Creates a continuous emitter of a `continuous` effect; its rate layers emit in every update().
   * Burst layers (count > 0) of the effect are spawned once. Returns a handle, or -1 when all
   * {@link MAX_PARTICLE_EMITTERS} emitters are in use.
   */
  createEmitter(effectIdx: number, posRaw: ArrayLike<number>, o?: ParticleSpawnOptions): number {
    const eff = this.lib.effects[effectIdx];
    if (eff === undefined) throw new RangeError(`ParticleSystem.createEmitter: unknown effect index ${effectIdx}`);
    if (!eff.continuous) throw new Error(`ParticleSystem.createEmitter: effect ${eff.id} is not continuous`);
    if (this.emFreeCount === 0) return -1;
    const e = this.emFree[--this.emFreeCount]!;
    this.emActive[e] = 1;
    this.emEffect[e] = effectIdx;
    const d = o?.dir;
    this.emDir[e * 3] = d !== undefined ? d[0]! : 0;
    this.emDir[e * 3 + 1] = d !== undefined ? d[1]! : 1;
    this.emDir[e * 3 + 2] = d !== undefined ? d[2]! : 0;
    this.emScale[e] = o?.scale ?? 1;
    this.emRate[e] = 1;
    this.emTint[e] = (o?.tint ?? 0xffffff) & 0xffffff;
    const seed = o?.seed;
    this.emSeed[e] = seed !== undefined ? hashHi24(seed >>> 0, effectIdx, 0xe417) : hashHi24(this.autoSeed++ & 0x3fffffff, effectIdx, 0xe418);
    this.emCounter[e] = 0;
    this.emAccum.fill(0, e * MAX_EFFECT_LAYERS, (e + 1) * MAX_EFFECT_LAYERS);
    this.emList[this.emCount] = e;
    this.emListPos[e] = this.emCount;
    this.emCount++;
    this.placeEmitter(e, posRaw, o?.targetRaw ?? posRaw);
    let hasBurst = false;
    for (let j = 0; j < eff.layerCount; j++) if (this.countMax[eff.firstLayer + j]! > 0) hasBurst = true;
    if (hasBurst) this.spawn(effectIdx, posRaw, o);
    return e | (this.emGen[e]! << EMITTER_BITS);
  }

  /** Stores position/target (raw) of emitter `e` and re-encodes its f16 vectors. */
  private placeEmitter(e: number, posRaw: ArrayLike<number>, targetRaw: ArrayLike<number> | undefined): void {
    const px = posRaw[0]! | 0;
    const py = posRaw[1]! | 0;
    const pz = posRaw[2]! | 0;
    const o = e * 3;
    this.emPos[o] = px;
    this.emPos[o + 1] = py;
    this.emPos[o + 2] = pz;
    if (targetRaw !== undefined) {
      this.emTarget[o] = targetRaw[0]! | 0;
      this.emTarget[o + 1] = targetRaw[1]! | 0;
      this.emTarget[o + 2] = targetRaw[2]! | 0;
    }
    const vin = this.vin;
    vin[V_TGT] = (this.emTarget[o]! - px) / 4096;
    vin[V_TGT + 1] = (this.emTarget[o + 1]! - py) / 4096;
    vin[V_TGT + 2] = (this.emTarget[o + 2]! - pz) / 4096;
    vin[V_DIR] = this.emDir[o]!;
    vin[V_DIR + 1] = this.emDir[o + 1]!;
    vin[V_DIR + 2] = this.emDir[o + 2]!;
    vin[V_SCALE] = this.emScale[e]!;
    this.encodeVectors(this.emHalfB, this.emHalfS, e * 4);
  }

  private emitterIndex(h: number): number {
    if (!Number.isInteger(h) || h < 0) return -1;
    const e = h & EMITTER_MASK;
    if (this.emActive[e] !== 1 || this.emGen[e] !== h >>> EMITTER_BITS) return -1;
    return e;
  }

  /**
   * Moves an emitter. With `targetRaw` the stream target moves too; without it the absolute target
   * stays where it was. Stale handles are ignored.
   */
  moveEmitter(h: number, posRaw: ArrayLike<number>, targetRaw?: ArrayLike<number>): void {
    const e = this.emitterIndex(h);
    if (e < 0) return;
    this.placeEmitter(e, posRaw, targetRaw);
  }

  /** Multiplies the emitter's rates by `scale` (0 pauses; e.g. build progress, damage level). */
  setEmitterRate(h: number, scale: number): void {
    const e = this.emitterIndex(h);
    if (e < 0) return;
    this.emRate[e] = scale > 0 && Number.isFinite(scale) ? scale : 0;
  }

  /** Stops an emitter; its particles live out their life. Stale handles are ignored. */
  destroyEmitter(h: number): void {
    const e = this.emitterIndex(h);
    if (e < 0) return;
    this.releaseEmitter(e);
  }

  /** True while the handle refers to a live emitter. */
  hasEmitter(h: number): boolean {
    return this.emitterIndex(h) >= 0;
  }

  private releaseEmitter(e: number): void {
    this.emActive[e] = 0;
    this.emGen[e] = (this.emGen[e]! + 1) & 0x3fffff;
    const pos = this.emListPos[e]!;
    const last = this.emList[--this.emCount]!;
    this.emList[pos] = last;
    this.emListPos[last] = pos;
    this.emFree[this.emFreeCount++] = e;
  }

  /** Continuous emission over the last tm[T_DT] seconds (clamped to MAX_EMIT_DT_S). */
  private runEmitters(): void {
    const tm = this.tm;
    let d = tm[T_DT]!;
    if (d <= 0 || this.emCount === 0) return;
    if (d > MAX_EMIT_DT_S) d = MAX_EMIT_DT_S;
    tm[T_START] = tm[T_NOW]! - d;
    tm[T_DT] = d;
    for (let k = 0; k < this.emCount; k++) {
      const e = this.emList[k]!;
      const eff = this.lib.effects[this.emEffect[e]!]!;
      const rs = this.emRate[e]!;
      if (rs <= 0) continue;
      const px = this.emPos[e * 3]!;
      const py = this.emPos[e * 3 + 1]!;
      const pz = this.emPos[e * 3 + 2]!;
      let vis = -1;
      for (let j = 0; j < eff.layerCount; j++) {
        const li = eff.firstLayer + j;
        const r = this.rate[li]! * rs;
        if (r <= 0) continue;
        const ai = e * MAX_EFFECT_LAYERS + j;
        const acc0 = this.emAccum[ai]!;
        const acc = acc0 + r * tm[T_DT]!;
        const n = Math.floor(acc);
        this.emAccum[ai] = acc - n;
        if (n <= 0) continue;
        if (vis < 0) {
          tm[T_RADIUS] = eff.boundsWu * this.emScale[e]!;
          vis = this.visibility(px, py, pz);
        }
        const allowed = this.admit(li, n, vis);
        const tint = this.emTint[e]!;
        const seedBase = this.emSeed[e]!;
        for (let i = 0; i < allowed; i++) {
          // Spread the kept particles evenly over the n emission instants of this frame.
          const kk = allowed === n ? i + 1 : Math.floor((i * n) / allowed) + 1;
          tm[T_T0] = tm[T_START]! + (kk - acc0) / r;
          const seed = (seedBase + this.emCounter[e]!++) & 0xffff;
          this.writeParticle(li, seed, px, py, pz, true, tint, this.emHalfB, this.emHalfS, e * 4);
        }
      }
    }
  }

  // ------------------------------------------------------------------------------------ frame

  /**
   * Per-frame CPU work: expiry (histogram + window tail), t0 of pending spawns, continuous
   * emitters, upload of the new records. `nowS` must be the clock the FxView block gets as
   * `timeS` (FxFrameUniforms.update) in the same frame. A clock that runs backwards clears the ring.
   * `camera` must be up to date (`camera.update()`, done by FxFrameUniforms.update); it is only
   * read for visibility culling.
   */
  update(nowS: number, camera: RtsCamera): void {
    if (this.destroyed) throw new Error('ParticleSystem: update after destroy');
    this.openFrame();
    const tm = this.tm;
    tm[T_T0] = nowS;
    if (this.hasTime && tm[T_T0]! < tm[T_NOW]! - 1e-6) {
      this.clearParticles();
      // The histogram clock only moves forward; restart it at the new time.
      this.curBucket = Math.floor(tm[T_T0]! * BUCKETS_PER_S);
    }
    tm[T_DT] = this.hasTime ? tm[T_T0]! - tm[T_NOW]! : 0;
    tm[T_NOW] = tm[T_T0]!;
    this.hasTime = true;

    this.readCamera(camera);
    this.expire();
    this.finalizePending();
    this.compact();
    this.frameOpen = true;
    this.runEmitters();
    this.flushUpload();
  }

  /** Frustum planes (Gribb/Hartmann, camera-relative like render's Frustum) and pixel scale. */
  private readCamera(camera: RtsCamera): void {
    const m = camera.viewProj;
    const p = this.planes;
    for (let i = 0; i < 6; i++) {
      const row = i >> 1;
      const sign = (i & 1) === 0 ? 1 : -1;
      const a = m[3]! + sign * m[row]!;
      const b = m[7]! + sign * m[4 + row]!;
      const c = m[11]! + sign * m[8 + row]!;
      const d = m[15]! + sign * m[12 + row]!;
      const l = Math.sqrt(a * a + b * b + c * c);
      const inv = l > 0 ? 1 / l : 1;
      p[i * 4] = a * inv;
      p[i * 4 + 1] = b * inv;
      p[i * 4 + 2] = c * inv;
      p[i * 4 + 3] = d * inv;
    }
    this.camInt[0] = camera.camPosInt[0]!;
    this.camInt[1] = camera.camPosInt[1]!;
    this.camInt[2] = camera.camPosInt[2]!;
    this.pxPerWu[0] = (0.5 * camera.viewportHeight) / Math.tan(camera.fovY / 2);
    this.hasCamera = true;
  }

  private expire(): void {
    const now = this.tm[T_NOW]!;
    const nb = Math.floor(now * BUCKETS_PER_S);
    if (nb > this.curBucket) {
      const steps = nb - this.curBucket > BUCKETS ? BUCKETS : nb - this.curBucket;
      for (let i = 0; i < steps; i++) {
        const k = (this.curBucket + i) & BUCKET_MASK;
        this.histAlive -= this.hist[k]!;
        this.hist[k] = 0;
      }
      this.curBucket = nb;
    }
    const cap = this.capacity;
    while (this.tail < this.pendingStart && this.expiry[this.tail % cap]! <= now) this.tail++;
  }

  private finalizePending(): void {
    if (this.pendingStart >= this.head) return;
    const now = this.tm[T_NOW]!;
    let t0w = now % FX_TIME_WRAP_S;
    if (t0w < 0) t0w += FX_TIME_WRAP_S;
    const f32 = this.views.f32;
    const cap = this.capacity;
    for (let c = this.pendingStart; c < this.head; c++) {
      const slot = c % cap;
      f32[slot * 8 + 3] = t0w;
      const exp = now + this.expiry[slot]!;
      this.expiry[slot] = exp;
      const bk = Math.floor(exp * BUCKETS_PER_S);
      if (bk >= this.curBucket) {
        this.hist[bk & BUCKET_MASK]!++;
        this.histAlive++;
      }
    }
    this.pendingStart = this.head;
  }

  /**
   * Uploads records [uploaded, head) with ≤ 2 writeBuffer calls (1 if the whole ring is new), plus
   * the range rewritten by full-ring evictions (≤ 2 more).
   */
  private flushUpload(): void {
    const cap = this.capacity;
    const start = Math.max(this.uploaded, this.head - cap);
    this.uploaded = this.head;
    // Evicted-into positions still inside the window and before the new range.
    let lo = this.dirtyLo;
    let hi = this.dirtyHi;
    this.dirtyLo = 0;
    this.dirtyHi = 0;
    if (lo < this.tail) lo = this.tail;
    if (hi > start) hi = start;
    if (hi > lo) this.uploadRange(lo, hi - lo);
    const n = this.head - start;
    if (n > 0) this.uploadRange(start, n);
  }

  /** Uploads `n` records starting at absolute position `start` (≤ 2 writeBuffer calls). */
  private uploadRange(start: number, n: number): void {
    const cap = this.capacity;
    const u8 = this.views.u8;
    const S = PARTICLE_RECORD_STRIDE;
    if (n >= cap) {
      this.dev.writeBuffer(this.ringBuf, 0, u8, 0, cap * S);
      n = cap;
    } else {
      const s0 = start % cap;
      const first = s0 + n <= cap ? n : cap - s0;
      this.dev.writeBuffer(this.ringBuf, s0 * S, u8, s0 * S, first * S);
      if (first < n) this.dev.writeBuffer(this.ringBuf, 0, u8, 0, (n - first) * S);
    }
    this.st.uploadBytesFrame += n * S;
  }

  /**
   * Draws the live window (1 draw, 2 when it wraps around the ring end; 0 when empty). Uploads
   * records spawned since update() first. Pass order (PLAN §3.7): … Units → Shields → Particles →
   * Beams/Trails → Post; depth test on, depth write off, blend 'premultiplied', no sorting.
   */
  encode(enc: PassEncoder): number {
    if (this.destroyed) throw new Error('ParticleSystem: encode after destroy');
    this.openFrame();
    this.finalizePending();
    this.flushUpload();
    this.frameOpen = false;
    this.frameClosed = true;
    const n = this.head - this.tail;
    let draws = 0;
    if (n > 0) {
      const cap = this.capacity;
      const t0 = this.tail % cap;
      const s = this.streams[0]!;
      enc.setPipeline(this.pipeline);
      enc.setBindGroup(this.group);
      const first = t0 + n <= cap ? n : cap - t0;
      s.offset = t0 * PARTICLE_RECORD_STRIDE;
      enc.setVertexStreams(this.streams);
      enc.drawInstanced(4, first);
      draws = 1;
      if (first < n) {
        s.offset = 0;
        enc.setVertexStreams(this.streams);
        enc.drawInstanced(4, n - first);
        draws = 2;
      }
    }
    this.st.draws = draws;
    return draws;
  }

  private clearParticles(): void {
    this.tail = this.head;
    this.pendingStart = this.head;
    this.uploaded = this.head;
    this.dirtyLo = 0;
    this.dirtyHi = 0;
    this.evictScan = this.head;
    this.hist.fill(0);
    this.histAlive = 0;
  }

  /** Removes every particle and every emitter (cumulative counters are kept). */
  clear(): void {
    this.clearParticles();
    for (let k = this.emCount - 1; k >= 0; k--) this.releaseEmitter(this.emList[k]!);
  }

  destroy(): void {
    if (this.destroyed) return;
    this.destroyed = true;
    const dev = this.dev;
    dev.destroyBindGroup(this.group);
    dev.destroyPipeline(this.pipeline);
    dev.destroyTexture(this.lutTex);
    dev.destroyTexture(this.layerTex);
    dev.destroyBuffer(this.ringBuf);
  }
}
