/**
 * Stateless GPU particle system (PLAN §3.7 "zustandsloser Spawn-Ring (64k, Cap nach Preset),
 * f(t−t0) im VS, Kurven-LUT, defineEffect-Daten, Prioritäten").
 *
 * - One instance vertex buffer holds `capacity` spawn records (record.ts, 32 B) plus a CPU mirror.
 *   Records are written once at spawn and never touched again: the vertex shader evaluates each
 *   particle as f(now − t0). Per frame only the NEW records are uploaded (≤ 2 writeBuffer when the
 *   range wraps around the ring end); the restore callback re-uploads the whole mirror, so particles
 *   keep flying after a context loss.
 * - The live window [tail, head) of the ring is drawn in one instanced draw (two when it wraps).
 *   Expired particles inside the window are degenerated by the vertex shader; the window's tail
 *   follows the expired slots.
 * - Alive counting without scanning: per-slot expiry (Float64Array) + a histogram of expiries in
 *   1/64 s buckets. A particle counts as alive until the end of its expiry bucket.
 * - Caps/priorities: priority 0 always spawns (overwrites the oldest slots when the ring is full),
 *   priority 1 while alive < cap, priority 2 while alive < 0.75·cap; priority-2 bursts outside the
 *   frustum or tiny on screen are culled, small ones thinned.
 * - Continuous emitters (≤ 1024): per-layer accumulators with sub-frame spawn times (no pulsing).
 */
import type { BindGroupH, BufH, GpuDevice, PassEncoder, PipeH, RenderPreset, RenderPresetName, RtsCamera, TexH, VertexStreamBinding } from '@faf/render';
import { Frustum, RENDER_PRESETS, SLOT_FRAME } from '@faf/render';
import { SLOT_FX_VIEW, UNIT_FX_CURVE_LUT } from '../core/slots.ts';
import type { FxBindings } from '../core/view.ts';
import { fxSharedBufferBindings } from '../core/view.ts';
import { wrapFxTime } from '../core/frame.ts';
import type { EffectDefCompiled, EffectLibrary } from '../effects/compile.ts';
import {
  L_COUNT_MAX,
  L_COUNT_MIN,
  L_DELAY_MAX,
  L_DELAY_MIN,
  L_LIFE_MAX,
  L_LIFE_MIN,
  L_MOTION,
  L_PRIORITY,
  L_RATE,
  LAYER_STRIDE,
  LAYER_TEXELS,
} from '../effects/compile.ts';
import { MAX_EFFECT_LAYERS } from '../effects/define.ts';
import { fxHash32 } from '../effects/random.ts';
import { toHalf } from '../core/half.ts';
import { PARTICLE_RECORD_STRIDE, PARTICLE_STREAM_LAYOUT, recordViews, writeRecord } from './record.ts';
import type { RecordViews } from './record.ts';
import { PARTICLE_FS, PARTICLE_VS } from './shaders.ts';

/**
 * Texture unit of the particle layer table (RGBA32F, texelFetch in the VS). Extension of the slot
 * table in core/slots.ts: units 10–14 are taken by the FX contract, 15 is the last unit WebGL2
 * guarantees (MAX_VERTEX_TEXTURE_IMAGE_UNITS ≥ 16).
 */
export const UNIT_FX_PARTICLE_LAYERS = 15;
/** Default ring size (PLAN §3.7: 64k). */
export const PARTICLE_RING_CAPACITY = 65536;
/** Maximum concurrent continuous emitters. */
export const MAX_PARTICLE_EMITTERS = 1024;
/** Expiry histogram resolution (s) and size (buckets; covers 128 s > max particle age 40 s + slack). */
export const EXPIRY_BUCKET_S = 1 / 64;
const BUCKETS = 8192;
const BUCKET_MASK = BUCKETS - 1;
const BUCKETS_PER_S = 64;
/** Priority 2 spawns only while alive < PRIO2_CAP_FRACTION · cap. */
export const PRIO2_CAP_FRACTION = 0.75;
/** Priority-2 bursts whose bounds sphere covers less than this many pixels (radius) are culled. */
export const CULL_RADIUS_PX = 1.5;
/** Below this on-screen radius (px) priority-2 bursts are thinned proportionally. */
export const THIN_RADIUS_PX = 8;
/** Largest time step used for continuous emission (avoids bursts after a stall). */
export const MAX_EMIT_DT_S = 0.25;

const EMITTER_BITS = 10;
const EMITTER_MASK = (1 << EMITTER_BITS) - 1;

/** Particle ring cap of a render preset (RENDER_PRESETS[p].caps.particles: low 8192 … ultra 65536). */
export function particleCapForPreset(p: RenderPresetName | RenderPreset): number {
  return typeof p === 'string' ? RENDER_PRESETS[p].caps.particles : p.caps.particles;
}

export interface ParticleSystemOptions {
  /** Ring size in records (default 65536). */
  readonly capacity?: number;
  /** Preset cap (`particleCapForPreset`), ≤ capacity. */
  readonly cap: number;
  /** Called by `spawn()` for effects with a `shake` definition (fx-lab: CameraShake.addFromEffect). */
  readonly onShake?: (effect: EffectDefCompiled, posRaw: Int32Array | readonly number[], tS: number) => void;
}

export interface ParticleSpawnOptions {
  /** Emission axis (unit vector, default +y). */
  readonly dir?: ArrayLike<number>;
  /** Effect scale (size, speed, emit radius, stream wave), default 1. */
  readonly scale?: number;
  /** Seed of the burst (default: internal deterministic counter). */
  readonly seed?: number;
  /** Spawn tint 0xRRGGBB for layers with tint 'spawn' (default 0xFFFFFF). */
  readonly tint?: number;
  /** Stream target (raw Q20.12) for layers with motion 'stream' (default = origin). */
  readonly targetRaw?: ArrayLike<number>;
}

export interface ParticleStats {
  /** Particles spawned and not yet expired (1/64 s resolution), including pending delays. */
  alive: number;
  cap: number;
  capacity: number;
  /** Particles written since the last encode(). */
  spawnedFrame: number;
  /** Requested particles per priority (cumulative). */
  requested: [number, number, number];
  /** Particles rejected by the cap per priority (cumulative). */
  dropped: [number, number, number];
  /** Priority-2 particles culled or thinned by visibility (cumulative). */
  culled: number;
  /** Bytes uploaded since the last encode(). */
  uploadBytesFrame: number;
  /** Active continuous emitters. */
  emitters: number;
  /** Still-alive slots overwritten because the ring was full (cumulative). */
  overwritten: number;
  /** Records in the drawn window [tail, head). */
  window: number;
  /** Draw calls of the last encode(). */
  draws: number;
}

export class ParticleSystem {
  readonly capacity: number;
  readonly lib: EffectLibrary;
  private cap: number;
  private readonly onShake: ParticleSystemOptions['onShake'];

  // ---- ring ----
  private readonly ring: ArrayBuffer;
  private readonly views: RecordViews;
  private readonly ringBuf: BufH;
  /** Absolute expiry time (s) per slot; relative lifetime (delay + life) while the slot is pending. */
  private readonly expiry: Float64Array;
  private head = 0;
  private tail = 0;
  /** First slot whose t0 is not assigned yet (spawned before this frame's update). */
  private pendingStart = 0;
  /** First slot not uploaded yet. */
  private uploaded = 0;

  // ---- alive histogram ----
  private readonly hist = new Int32Array(BUCKETS);
  private histAlive = 0;
  private curBucket = 0;

  // ---- time / frame state ----
  private nowS = 0;
  private hasTime = false;
  private frameOpen = false;
  private frameClosed = true;
  private autoSeed = 0;

  // ---- camera (culling) ----
  private readonly frustum = new Frustum();
  private readonly camInt = new Int32Array(3);
  private pxPerWu = 0;
  private hasCamera = false;

  // ---- layer / effect caches ----
  private readonly lifeMin: Float64Array;
  private readonly lifeRange: Float64Array;
  private readonly delayMin: Float64Array;
  private readonly delayRange: Float64Array;
  private readonly prio: Uint8Array;
  private readonly isStream: Uint8Array;
  private readonly rate: Float64Array;
  private readonly countMin: Int32Array;
  private readonly countMax: Int32Array;

  // ---- emitters ----
  private readonly emActive = new Uint8Array(MAX_PARTICLE_EMITTERS);
  private readonly emGen = new Uint32Array(MAX_PARTICLE_EMITTERS);
  private readonly emEffect = new Int32Array(MAX_PARTICLE_EMITTERS);
  private readonly emPos = new Int32Array(MAX_PARTICLE_EMITTERS * 3);
  private readonly emTarget = new Int32Array(MAX_PARTICLE_EMITTERS * 3);
  private readonly emDir = new Float64Array(MAX_PARTICLE_EMITTERS * 3);
  private readonly emScale = new Float64Array(MAX_PARTICLE_EMITTERS);
  private readonly emRate = new Float64Array(MAX_PARTICLE_EMITTERS);
  private readonly emTint = new Int32Array(MAX_PARTICLE_EMITTERS);
  private readonly emSeed = new Uint32Array(MAX_PARTICLE_EMITTERS);
  private readonly emCounter = new Uint32Array(MAX_PARTICLE_EMITTERS);
  private readonly emAccum = new Float64Array(MAX_PARTICLE_EMITTERS * MAX_EFFECT_LAYERS);
  /** Dense list of active emitter indices + position of each index in it. */
  private readonly emList = new Int32Array(MAX_PARTICLE_EMITTERS);
  private readonly emListPos = new Int32Array(MAX_PARTICLE_EMITTERS);
  private emCount = 0;
  private readonly emFree = new Int32Array(MAX_PARTICLE_EMITTERS);
  private emFreeCount = MAX_PARTICLE_EMITTERS;

  // ---- GPU ----
  private readonly dev: GpuDevice;
  private readonly lutTex: TexH;
  private readonly layerTex: TexH;
  private readonly pipeline: PipeH;
  private readonly group: BindGroupH;
  private readonly streams: VertexStreamBinding[];
  private destroyed = false;

  // ---- scratch ----
  private readonly halfB = new Uint16Array(4);
  private readonly halfS = new Uint16Array(4);
  private readonly shakePos = new Int32Array(3);
  private readonly st: ParticleStats;

  constructor(dev: GpuDevice, bindings: FxBindings, lib: EffectLibrary, opts: ParticleSystemOptions) {
    const capacity = opts.capacity ?? PARTICLE_RING_CAPACITY;
    if (!Number.isInteger(capacity) || capacity < 1 || capacity > 1 << 20) {
      throw new RangeError(`ParticleSystem: capacity ${capacity} outside [1, 2^20]`);
    }
    if (lib.layerCount < 1) throw new Error('ParticleSystem: effect library has no layers');
    this.dev = dev;
    this.lib = lib;
    this.capacity = capacity;
    this.cap = this.checkCap(opts.cap);
    this.onShake = opts.onShake;

    const n = lib.layerCount;
    this.lifeMin = new Float64Array(n);
    this.lifeRange = new Float64Array(n);
    this.delayMin = new Float64Array(n);
    this.delayRange = new Float64Array(n);
    this.prio = new Uint8Array(n);
    this.isStream = new Uint8Array(n);
    this.rate = new Float64Array(n);
    this.countMin = new Int32Array(n);
    this.countMax = new Int32Array(n);
    const L = lib.layers;
    for (let i = 0; i < n; i++) {
      const o = i * LAYER_STRIDE;
      // Same f32 values the shader reads from the layer texture.
      this.lifeMin[i] = L[o + L_LIFE_MIN]!;
      this.lifeRange[i] = L[o + L_LIFE_MAX]! - L[o + L_LIFE_MIN]!;
      this.delayMin[i] = L[o + L_DELAY_MIN]!;
      this.delayRange[i] = L[o + L_DELAY_MAX]! - L[o + L_DELAY_MIN]!;
      this.prio[i] = L[o + L_PRIORITY]!;
      this.isStream[i] = L[o + L_MOTION]! > 0.5 ? 1 : 0;
      this.rate[i] = L[o + L_RATE]!;
      this.countMin[i] = L[o + L_COUNT_MIN]!;
      this.countMax[i] = L[o + L_COUNT_MAX]!;
    }
    for (const e of lib.effects) {
      if (e.layerCount > MAX_EFFECT_LAYERS) throw new Error(`ParticleSystem: effect ${e.id} has > ${MAX_EFFECT_LAYERS} layers`);
    }

    this.ring = new ArrayBuffer(capacity * PARTICLE_RECORD_STRIDE);
    this.views = recordViews(this.ring);
    this.expiry = new Float64Array(capacity);
    for (let i = 0; i < MAX_PARTICLE_EMITTERS; i++) this.emFree[i] = MAX_PARTICLE_EMITTERS - 1 - i;

    this.ringBuf = dev.createBuffer({
      label: 'fx.particles.ring',
      usage: 'vertex',
      size: capacity * PARTICLE_RECORD_STRIDE,
      dynamic: true,
      // Whole mirror: records are immutable after spawn, so this restores every live particle.
      restore: (h) => dev.writeBuffer(h, 0, this.views.u8),
    });
    const lut = lib.lut;
    this.lutTex = dev.createTexture({
      label: 'fx.particles.lut',
      width: lut.width,
      height: lut.height,
      format: 'rgba16f',
      filter: 'linear',
      wrap: 'clamp',
      restore: (h) => dev.writeTexture(h, { x: 0, y: 0, width: lut.width, height: lut.height }, lut.data),
    });
    dev.writeTexture(this.lutTex, { x: 0, y: 0, width: lut.width, height: lut.height }, lut.data);
    const layerData = lib.layers.subarray(0, n * LAYER_STRIDE);
    this.layerTex = dev.createTexture({
      label: 'fx.particles.layers',
      width: LAYER_TEXELS,
      height: n,
      format: 'rgba32f',
      filter: 'nearest',
      wrap: 'clamp',
      restore: (h) => dev.writeTexture(h, { x: 0, y: 0, width: LAYER_TEXELS, height: n }, layerData),
    });
    dev.writeTexture(this.layerTex, { x: 0, y: 0, width: LAYER_TEXELS, height: n }, layerData);
    this.pipeline = dev.createPipeline({
      label: 'fx.particles',
      vertex: PARTICLE_VS,
      fragment: PARTICLE_FS,
      streams: [PARTICLE_STREAM_LAYOUT],
      uniformBlocks: [
        { name: 'Frame', slot: SLOT_FRAME },
        { name: 'FxView', slot: SLOT_FX_VIEW },
      ],
      samplers: [
        { name: 'u_fxCurveLut', unit: UNIT_FX_CURVE_LUT },
        { name: 'u_fxParticleLayers', unit: UNIT_FX_PARTICLE_LAYERS },
      ],
      primitive: 'triangle-strip',
      cullMode: 'none',
      depthTest: true,
      depthWrite: false,
      blend: 'premultiplied',
    });
    this.group = dev.createBindGroup({
      label: 'fx.particles',
      buffers: fxSharedBufferBindings(bindings),
      textures: [
        { unit: UNIT_FX_CURVE_LUT, texture: this.lutTex },
        { unit: UNIT_FX_PARTICLE_LAYERS, texture: this.layerTex },
      ],
    });
    this.streams = [{ buffer: this.ringBuf, offset: 0 }];
    this.st = {
      alive: 0,
      cap: this.cap,
      capacity,
      spawnedFrame: 0,
      requested: [0, 0, 0],
      dropped: [0, 0, 0],
      culled: 0,
      uploadBytesFrame: 0,
      emitters: 0,
      overwritten: 0,
      window: 0,
      draws: 0,
    };
  }

  private checkCap(n: number): number {
    if (!Number.isInteger(n) || n < 0 || n > this.capacity) {
      throw new RangeError(`ParticleSystem: cap ${n} outside [0, ${this.capacity}]`);
    }
    return n;
  }

  /** Changes the preset cap (0 ≤ n ≤ capacity). Particles above the new cap live out their life. */
  setCap(n: number): void {
    this.cap = this.checkCap(n);
  }

  /** Live counters (the same object every call, updated in place). */
  get stats(): Readonly<ParticleStats> {
    const s = this.st;
    s.alive = this.aliveTotal();
    s.cap = this.cap;
    s.emitters = this.emCount;
    s.window = this.head - this.tail;
    return s;
  }

  /** Current particle clock (s) – the `nowS` of the last update(). */
  get timeS(): number {
    return this.nowS;
  }

  /** CPU mirror of the ring (tests, debugging). */
  get records(): RecordViews {
    return this.views;
  }

  /** Ring positions of the drawn window: slots [tail, head) modulo capacity (tests). */
  get windowRange(): { readonly tail: number; readonly head: number } {
    return { tail: this.tail, head: this.head };
  }

  /** Absolute expiry time of ring slot `slot` (tests). */
  expiryOf(slot: number): number {
    return this.expiry[slot]!;
  }

  private aliveTotal(): number {
    return this.histAlive + (this.head - this.pendingStart);
  }

  private openFrame(): void {
    if (!this.frameClosed) return;
    this.frameClosed = false;
    this.st.spawnedFrame = 0;
    this.st.uploadBytesFrame = 0;
  }

  // ------------------------------------------------------------------------------------ spawning

  /**
   * Spawns a burst of effect `effectIdx` at `posRaw` (raw Q20.12). Before `update()` of a frame the
   * records are pending and get this frame's time in `update()`; between `update()` and `encode()`
   * they get the current time directly. Either way they are uploaded and drawn in the same frame.
   * Returns the number of particles written.
   */
  spawn(effectIdx: number, posRaw: ArrayLike<number>, o?: ParticleSpawnOptions): number {
    const eff = this.lib.effects[effectIdx];
    if (eff === undefined) throw new RangeError(`ParticleSystem.spawn: unknown effect index ${effectIdx}`);
    this.openFrame();
    const seed = o?.seed;
    const seedBase = seed !== undefined ? fxHash32(seed >>> 0, effectIdx, 0x5eed) : fxHash32(this.autoSeed++, effectIdx, 0xa070);
    const scale = o?.scale ?? 1;
    const px = posRaw[0]! | 0;
    const py = posRaw[1]! | 0;
    const pz = posRaw[2]! | 0;
    this.encodeVectors(o?.dir, scale, px, py, pz, o?.targetRaw);
    const tint = (o?.tint ?? 0xffffff) & 0xffffff;
    const vis = this.visibility(px, py, pz, eff.boundsWu * scale);
    const final = this.frameOpen;
    const t0Abs = this.nowS;
    const t0w = wrapFxTime(t0Abs);
    let total = 0;
    for (let j = 0; j < eff.layerCount; j++) {
      const li = eff.firstLayer + j;
      const cMin = this.countMin[li]!;
      const cMax = this.countMax[li]!;
      if (cMax <= 0) continue;
      const n = cMin + Math.floor(((fxHash32(seedBase, li, 0xc0) >>> 8) / 16777216) * (cMax - cMin + 1));
      const allowed = this.admit(li, n, vis);
      const lseed = fxHash32(seedBase, li, 0x51);
      for (let i = 0; i < allowed; i++) {
        this.writeParticle(li, (lseed + i) & 0xffff, px, py, pz, t0Abs, t0w, final, tint);
      }
      total += allowed;
    }
    if (eff.shake !== null && this.onShake !== undefined) {
      const sp = this.shakePos;
      sp[0] = px;
      sp[1] = py;
      sp[2] = pz;
      this.onShake(eff, sp, this.nowS);
    }
    return total;
  }

  /**
   * Applies visibility culling (priority 2) and the cap rules to a request of `n` particles of layer
   * `li`; updates requested/dropped/culled and returns how many may be written.
   */
  private admit(li: number, n: number, vis: number): number {
    if (n <= 0) return 0;
    const p = this.prio[li]!;
    const st = this.st;
    st.requested[p]! += n;
    if (p === 2 && vis < 1) {
      const keep = vis <= 0 ? 0 : Math.floor(n * vis + 0.5);
      st.culled += n - keep;
      n = keep;
      if (n === 0) return 0;
    }
    if (p === 0) return n;
    const limit = p === 1 ? this.cap : Math.floor(PRIO2_CAP_FRACTION * this.cap);
    const room = limit - this.aliveTotal();
    const allowed = room <= 0 ? 0 : room < n ? room : n;
    st.dropped[p]! += n - allowed;
    return allowed;
  }

  /**
   * 1 = fully visible, 0 = cull, (0, 1) = thinning factor for priority-2 particles of a burst with
   * bounds radius `rWu` at raw position (x, y, z). Without a camera (no update yet) everything is visible.
   */
  private visibility(x: number, y: number, z: number, rWu: number): number {
    if (!this.hasCamera) return 1;
    const rx = (x - this.camInt[0]!) / 4096;
    const ry = (y - this.camInt[1]!) / 4096;
    const rz = (z - this.camInt[2]!) / 4096;
    if (!this.frustum.sphereVisible(rx, ry, rz, rWu)) return 0;
    const dist = Math.sqrt(rx * rx + ry * ry + rz * rz);
    if (dist <= rWu) return 1;
    const px = (rWu * this.pxPerWu) / dist;
    if (px < CULL_RADIUS_PX) return 0;
    if (px < THIN_RADIUS_PX) return px / THIN_RADIUS_PX;
    return 1;
  }

  /** Fills halfB (ballistic: unit axis + scale) and halfS (stream: target delta + scale). */
  private encodeVectors(
    dir: ArrayLike<number> | undefined,
    scale: number,
    px: number,
    py: number,
    pz: number,
    targetRaw: ArrayLike<number> | undefined,
  ): void {
    let dx = 0;
    let dy = 1;
    let dz = 0;
    if (dir !== undefined) {
      const l = Math.sqrt(dir[0]! * dir[0]! + dir[1]! * dir[1]! + dir[2]! * dir[2]!);
      if (l > 1e-9) {
        dx = dir[0]! / l;
        dy = dir[1]! / l;
        dz = dir[2]! / l;
      }
    }
    const hs = toHalf(scale);
    const hb = this.halfB;
    hb[0] = toHalf(dx);
    hb[1] = toHalf(dy);
    hb[2] = toHalf(dz);
    hb[3] = hs;
    const hsT = this.halfS;
    if (targetRaw !== undefined) {
      hsT[0] = toHalf((targetRaw[0]! - px) / 4096);
      hsT[1] = toHalf((targetRaw[1]! - py) / 4096);
      hsT[2] = toHalf((targetRaw[2]! - pz) / 4096);
    } else {
      hsT[0] = 0;
      hsT[1] = 0;
      hsT[2] = 0;
    }
    hsT[3] = hs;
  }

  /** Writes one record at the ring head (evicting the oldest slot when the ring is full). */
  private writeParticle(li: number, seed: number, px: number, py: number, pz: number, t0Abs: number, t0w: number, final: boolean, tint: number): void {
    if (this.head - this.tail >= this.capacity) this.evictOldest();
    const slot = this.head % this.capacity;
    const hv = this.isStream[li] === 1 ? this.halfS : this.halfB;
    writeRecord(this.views, slot, px, py, pz, final ? t0w : 0, hv[0]!, hv[1]!, hv[2]!, hv[3]!, li, seed, tint);
    // Same randoms as the shader: uLife = lo(h0), uDelay = lo(h4).
    const uLife = (fxHash32(seed, li, 0) & 0xffff) / 65536;
    const uDelay = (fxHash32(seed, li, 4) & 0xffff) / 65536;
    const rel = this.delayMin[li]! + this.delayRange[li]! * uDelay + this.lifeMin[li]! + this.lifeRange[li]! * uLife;
    if (final) {
      const exp = t0Abs + rel;
      this.expiry[slot] = exp;
      this.histAdd(exp);
    } else {
      this.expiry[slot] = rel;
    }
    this.head++;
    // Final records only appear while no record is pending (pending records form a suffix).
    if (final) this.pendingStart = this.head;
    this.st.spawnedFrame++;
  }

  private histAdd(exp: number): void {
    const b = Math.floor(exp * BUCKETS_PER_S);
    if (b < this.curBucket) return; // already expired (sub-frame emission at the end of its life)
    this.hist[b & BUCKET_MASK]!++;
    this.histAlive++;
  }

  private evictOldest(): void {
    const slot = this.tail % this.capacity;
    if (this.tail < this.pendingStart) {
      const b = Math.floor(this.expiry[slot]! * BUCKETS_PER_S);
      if (b >= this.curBucket) {
        this.hist[b & BUCKET_MASK]!--;
        this.histAlive--;
        this.st.overwritten++;
      }
    } else {
      this.pendingStart = this.tail + 1;
      this.st.overwritten++;
    }
    this.tail++;
  }

  // ------------------------------------------------------------------------------------ emitters

  /**
   * Creates a continuous emitter of a `continuous` effect; its rate layers emit in every update().
   * Burst layers (count > 0) of the effect are spawned once. Returns a handle, or -1 when all
   * {@link MAX_PARTICLE_EMITTERS} emitters are in use.
   */
  createEmitter(effectIdx: number, posRaw: ArrayLike<number>, o?: ParticleSpawnOptions): number {
    const eff = this.lib.effects[effectIdx];
    if (eff === undefined) throw new RangeError(`ParticleSystem.createEmitter: unknown effect index ${effectIdx}`);
    if (!eff.continuous) throw new Error(`ParticleSystem.createEmitter: effect ${eff.id} is not continuous`);
    if (this.emFreeCount === 0) return -1;
    const e = this.emFree[--this.emFreeCount]!;
    this.emActive[e] = 1;
    this.emEffect[e] = effectIdx;
    this.emPos[e * 3] = posRaw[0]! | 0;
    this.emPos[e * 3 + 1] = posRaw[1]! | 0;
    this.emPos[e * 3 + 2] = posRaw[2]! | 0;
    const t = o?.targetRaw ?? posRaw;
    this.emTarget[e * 3] = t[0]! | 0;
    this.emTarget[e * 3 + 1] = t[1]! | 0;
    this.emTarget[e * 3 + 2] = t[2]! | 0;
    const d = o?.dir;
    this.emDir[e * 3] = d?.[0] ?? 0;
    this.emDir[e * 3 + 1] = d?.[1] ?? 1;
    this.emDir[e * 3 + 2] = d?.[2] ?? 0;
    this.emScale[e] = o?.scale ?? 1;
    this.emRate[e] = 1;
    this.emTint[e] = (o?.tint ?? 0xffffff) & 0xffffff;
    const seed = o?.seed;
    this.emSeed[e] = seed !== undefined ? fxHash32(seed >>> 0, effectIdx, 0xe417) : fxHash32(this.autoSeed++, effectIdx, 0xe418);
    this.emCounter[e] = 0;
    this.emAccum.fill(0, e * MAX_EFFECT_LAYERS, (e + 1) * MAX_EFFECT_LAYERS);
    this.emList[this.emCount] = e;
    this.emListPos[e] = this.emCount;
    this.emCount++;
    let hasBurst = false;
    for (let j = 0; j < eff.layerCount; j++) if (this.countMax[eff.firstLayer + j]! > 0) hasBurst = true;
    if (hasBurst) this.spawn(effectIdx, posRaw, o);
    return e | (this.emGen[e]! << EMITTER_BITS);
  }

  private emitterIndex(h: number): number {
    if (!Number.isInteger(h) || h < 0) return -1;
    const e = h & EMITTER_MASK;
    if (this.emActive[e] !== 1 || this.emGen[e] !== h >>> EMITTER_BITS) return -1;
    return e;
  }

  /** Moves an emitter (and its stream target). Stale handles are ignored. */
  moveEmitter(h: number, posRaw: ArrayLike<number>, targetRaw?: ArrayLike<number>): void {
    const e = this.emitterIndex(h);
    if (e < 0) return;
    this.emPos[e * 3] = posRaw[0]! | 0;
    this.emPos[e * 3 + 1] = posRaw[1]! | 0;
    this.emPos[e * 3 + 2] = posRaw[2]! | 0;
    if (targetRaw !== undefined) {
      this.emTarget[e * 3] = targetRaw[0]! | 0;
      this.emTarget[e * 3 + 1] = targetRaw[1]! | 0;
      this.emTarget[e * 3 + 2] = targetRaw[2]! | 0;
    }
  }

  /** Multiplies the emitter's rates by `scale` (0 pauses; e.g. build progress, damage level). */
  setEmitterRate(h: number, scale: number): void {
    const e = this.emitterIndex(h);
    if (e < 0) return;
    this.emRate[e] = scale > 0 && Number.isFinite(scale) ? scale : 0;
  }

  /** Stops an emitter; its particles live out their life. Stale handles are ignored. */
  destroyEmitter(h: number): void {
    const e = this.emitterIndex(h);
    if (e < 0) return;
    this.releaseEmitter(e);
  }

  /** True while the handle refers to a live emitter. */
  hasEmitter(h: number): boolean {
    return this.emitterIndex(h) >= 0;
  }

  private releaseEmitter(e: number): void {
    this.emActive[e] = 0;
    this.emGen[e] = (this.emGen[e]! + 1) & 0x3fffff;
    const pos = this.emListPos[e]!;
    const last = this.emList[--this.emCount]!;
    this.emList[pos] = last;
    this.emListPos[last] = pos;
    this.emFree[this.emFreeCount++] = e;
  }

  private runEmitters(dt: number): void {
    if (dt <= 0 || this.emCount === 0) return;
    const d = dt > MAX_EMIT_DT_S ? MAX_EMIT_DT_S : dt;
    const start = this.nowS - d;
    for (let k = 0; k < this.emCount; k++) {
      const e = this.emList[k]!;
      const eff = this.lib.effects[this.emEffect[e]!]!;
      const rs = this.emRate[e]!;
      if (rs <= 0) continue;
      const px = this.emPos[e * 3]!;
      const py = this.emPos[e * 3 + 1]!;
      const pz = this.emPos[e * 3 + 2]!;
      const scale = this.emScale[e]!;
      let prepared = false;
      let vis = 1;
      for (let j = 0; j < eff.layerCount; j++) {
        const li = eff.firstLayer + j;
        const r = this.rate[li]! * rs;
        if (r <= 0) continue;
        const ai = e * MAX_EFFECT_LAYERS + j;
        const acc0 = this.emAccum[ai]!;
        const acc = acc0 + r * d;
        const n = Math.floor(acc);
        this.emAccum[ai] = acc - n;
        if (n <= 0) continue;
        if (!prepared) {
          prepared = true;
          const dirO = e * 3;
          this.dirScratch[0] = this.emDir[dirO]!;
          this.dirScratch[1] = this.emDir[dirO + 1]!;
          this.dirScratch[2] = this.emDir[dirO + 2]!;
          this.tgtScratch[0] = this.emTarget[dirO]!;
          this.tgtScratch[1] = this.emTarget[dirO + 1]!;
          this.tgtScratch[2] = this.emTarget[dirO + 2]!;
          this.encodeVectors(this.dirScratch, scale, px, py, pz, this.tgtScratch);
          vis = this.visibility(px, py, pz, eff.boundsWu * scale);
        }
        const allowed = this.admit(li, n, vis);
        const tint = this.emTint[e]!;
        const seedBase = this.emSeed[e]!;
        for (let i = 0; i < allowed; i++) {
          // Spread the kept particles evenly over the n emission instants of this frame.
          const kk = allowed === n ? i + 1 : Math.floor((i * n) / allowed) + 1;
          const t0Abs = start + (kk - acc0) / r;
          const seed = (seedBase + this.emCounter[e]!++) & 0xffff;
          this.writeParticle(li, seed, px, py, pz, t0Abs, wrapFxTime(t0Abs), true, tint);
        }
      }
    }
  }

  private readonly dirScratch = new Float64Array(3);
  private readonly tgtScratch = new Int32Array(3);

  // ------------------------------------------------------------------------------------ frame

  /**
   * Per-frame CPU work: expiry (histogram + window tail), t0 of pending spawns, continuous
   * emitters, upload of the new records. `nowS` must be the clock the FxView block gets as
   * `timeS` (FxFrameUniforms.update) in the same frame. A clock that runs backwards clears the ring.
   */
  update(nowS: number, camera: RtsCamera): void {
    if (this.destroyed) throw new Error('ParticleSystem: update after destroy');
    this.openFrame();
    if (this.hasTime && nowS < this.nowS - 1e-6) this.clearParticles();
    const prev = this.nowS;
    const dt = this.hasTime ? nowS - prev : 0;
    this.nowS = nowS;
    this.hasTime = true;

    camera.update();
    this.frustum.setFromViewProj(camera.viewProj);
    this.camInt[0] = camera.camPosInt[0]!;
    this.camInt[1] = camera.camPosInt[1]!;
    this.camInt[2] = camera.camPosInt[2]!;
    this.pxPerWu = (0.5 * camera.viewportHeight) / Math.tan(camera.fovY / 2);
    this.hasCamera = true;

    this.expire(nowS);
    this.finalizePending(nowS);
    this.frameOpen = true;
    this.runEmitters(dt);
    this.flushUpload();
  }

  private expire(now: number): void {
    const nb = Math.floor(now * BUCKETS_PER_S);
    if (nb > this.curBucket) {
      const steps = nb - this.curBucket > BUCKETS ? BUCKETS : nb - this.curBucket;
      for (let i = 0; i < steps; i++) {
        const k = (this.curBucket + i) & BUCKET_MASK;
        this.histAlive -= this.hist[k]!;
        this.hist[k] = 0;
      }
      this.curBucket = nb;
    }
    const cap = this.capacity;
    while (this.tail < this.pendingStart && this.expiry[this.tail % cap]! <= now) this.tail++;
  }

  private finalizePending(now: number): void {
    if (this.pendingStart >= this.head) return;
    const t0w = wrapFxTime(now);
    const f32 = this.views.f32;
    const cap = this.capacity;
    for (let c = this.pendingStart; c < this.head; c++) {
      const slot = c % cap;
      f32[slot * 8 + 3] = t0w;
      const exp = now + this.expiry[slot]!;
      this.expiry[slot] = exp;
      this.histAdd(exp);
    }
    this.pendingStart = this.head;
  }

  /** Uploads records [uploaded, head) with ≤ 2 writeBuffer calls (1 if the whole ring is new). */
  private flushUpload(): void {
    const cap = this.capacity;
    const start = Math.max(this.uploaded, this.head - cap);
    const n = this.head - start;
    this.uploaded = this.head;
    if (n <= 0) return;
    const u8 = this.views.u8;
    const S = PARTICLE_RECORD_STRIDE;
    if (n >= cap) {
      this.dev.writeBuffer(this.ringBuf, 0, u8, 0, cap * S);
    } else {
      const s0 = start % cap;
      const first = s0 + n <= cap ? n : cap - s0;
      this.dev.writeBuffer(this.ringBuf, s0 * S, u8, s0 * S, first * S);
      if (first < n) this.dev.writeBuffer(this.ringBuf, 0, u8, 0, (n - first) * S);
    }
    this.st.uploadBytesFrame += n * S;
  }

  /**
   * Draws the live window (1 draw, 2 when it wraps around the ring end; 0 when empty). Uploads
   * records spawned since update() first. Pass order (PLAN §3.7): … Units → Shields → Particles →
   * Beams/Trails → Post; depth test on, depth write off, blend 'premultiplied', no sorting.
   */
  encode(enc: PassEncoder): number {
    if (this.destroyed) throw new Error('ParticleSystem: encode after destroy');
    this.openFrame();
    this.finalizePending(this.nowS);
    this.flushUpload();
    this.frameOpen = false;
    this.frameClosed = true;
    const n = this.head - this.tail;
    let draws = 0;
    if (n > 0) {
      const cap = this.capacity;
      const t0 = this.tail % cap;
      const s = this.streams[0]!;
      enc.setPipeline(this.pipeline);
      enc.setBindGroup(this.group);
      const first = t0 + n <= cap ? n : cap - t0;
      s.offset = t0 * PARTICLE_RECORD_STRIDE;
      enc.setVertexStreams(this.streams);
      enc.drawInstanced(4, first);
      draws = 1;
      if (first < n) {
        s.offset = 0;
        enc.setVertexStreams(this.streams);
        enc.drawInstanced(4, n - first);
        draws = 2;
      }
    }
    this.st.draws = draws;
    return draws;
  }

  private clearParticles(): void {
    this.tail = this.head;
    this.pendingStart = this.head;
    this.uploaded = this.head;
    this.hist.fill(0);
    this.histAlive = 0;
  }

  /** Removes every particle and every emitter (cumulative counters are kept). */
  clear(): void {
    this.clearParticles();
    for (let k = this.emCount - 1; k >= 0; k--) this.releaseEmitter(this.emList[k]!);
  }

  destroy(): void {
    if (this.destroyed) return;
    this.destroyed = true;
    const dev = this.dev;
    dev.destroyBindGroup(this.group);
    dev.destroyPipeline(this.pipeline);
    dev.destroyTexture(this.lutTex);
    dev.destroyTexture(this.layerTex);
    dev.destroyBuffer(this.ringBuf);
  }
}
